// Command doom runs the DOOM shareware episode as pure Go.
// The ./doom package is dewasm's conversion of jacobenget/doom.wasm.
// That is doom_gen.go, regenerated by build.sh.
// It comes together with the ebiten frontend that drives it.
//
// Run with -smoke for a headless self-check; see ./doom for the frontend itself.
package main

import "doom-example/doom"

func main() {
	doom.Run()
}
