// Command doom runs the DOOM shareware episode as pure Go: the ./doom package is dewasm's conversion of jacobenget/doom.wasm (doom_gen.go, regenerated by build.sh) together with the ebiten frontend that drives it.
//
// Run with -smoke for a headless self-check; see ./doom for the frontend itself.
package main

import "doom-example/doom"

func main() {
	doom.Run()
}
