//! The two outputs of `cargo xtask size`: the machine-readable record under `records/` and the generated `docs/sizes/results.md`.
//!
//! Same discipline as the benchmark record: a measurement, not a compared snapshot, so no freshness test guards either file.
//! The JSON is the record (host, every runtime's version string as captured by executing it, every counted file), and the markdown is a rendering of it: numbers, not prose.
//! What the numbers mean, how to run the command and what the measurement does not include are in the hand-written `docs/sizes/README.md`, which this module never touches.

use std::fmt::Write as _;

use serde::{Deserialize, Serialize};

use crate::bench::chart::round3;
use crate::bench::report::Host;
use crate::size::chart::Chart;

/// The full size record.
/// `schema` exists so a later reader can tell an old record from a new one.
#[derive(Serialize, Deserialize)]
pub struct Report {
    pub schema: u32,
    /// UTC, `YYYY-MM-DDTHH:MM:SSZ`.
    pub generated_at: String,
    pub host: Host,
    /// Every native runtime, available or not, in matrix order.
    pub runtimes: Vec<Runtime>,
    pub apps: Vec<App>,
}

#[derive(Serialize, Deserialize)]
pub struct Runtime {
    pub runtime: String,
    /// Captured by running the runtime, not hardcoded.
    pub version: Option<String>,
    /// Every file counted into the total, so the accounting can be checked against the host.
    #[serde(default)]
    pub components: Vec<Component>,
    #[serde(flatten)]
    pub outcome: Outcome,
}

/// One file counted into a runtime's size: the resolved executable, or a shared library beside it.
#[derive(Serialize, Deserialize)]
pub struct Component {
    pub path: String,
    pub bytes: u64,
}

#[derive(Serialize, Deserialize)]
pub struct App {
    /// Cache stem, e.g. `cowsay`.
    pub app: String,
    /// The file in `examples/apps/cache/`.
    pub file: String,
    /// The wasm binary's own size, or why it could not be weighed.
    pub wasm: Outcome,
    /// One entry per backend, in matrix order.
    pub targets: Vec<Cell>,
}

#[derive(Serialize, Deserialize)]
pub struct Cell {
    pub target: String,
    #[serde(flatten)]
    pub outcome: Outcome,
}

#[derive(Serialize, Deserialize)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum Outcome {
    Ok {
        bytes: u64,
    },
    /// Deliberately not weighed (an uninstalled runtime, a cache file that is not there).
    /// Always reported, never silently dropped.
    Skipped {
        reason: String,
    },
    /// Attempted and broke: a conversion error lands here.
    Failed {
        reason: String,
    },
}

impl Outcome {
    pub fn bytes(&self) -> Option<u64> {
        match self {
            Outcome::Ok { bytes } => Some(*bytes),
            _ => None,
        }
    }
}

impl Report {
    /// Pretty-printed JSON, newline-terminated.
    pub fn to_json(&self) -> anyhow::Result<String> {
        let mut text = serde_json::to_string_pretty(self)?;
        text.push('\n');
        Ok(text)
    }
}

/// Render `docs/sizes/results.md`: the layout of `docs/benchmarks/results.md`: the generated-file marker, two sentences pointing at the hand-written README, then the environment and the numbers.
/// No explanatory prose: what the figures mean belongs in `docs/sizes/README.md`, which a person edits.
pub fn render_doc(report: &Report, charts: &[Chart]) -> String {
    let mut out = String::new();
    out.push_str("# Sizes\n\n");
    out.push_str("<!-- AUTO-GENERATED by `cargo xtask size`; do not edit by hand. Unlike docs/support.md there is no freshness test: sizes depend on the host's installed runtimes, so this file is a dated measurement, not a compared snapshot. -->\n\n");
    out.push_str("What it costs to distribute a wasm program, taken on one host on one day: the wasm binary plus a runtime that can execute it, against the source dewasm converts that same binary into.\nHow to run and read these measurements is [README.md](README.md).\n\n");

    render_environment(&mut out, report);
    render_results(&mut out, report, charts);
    render_gaps(&mut out, report);
    out
}

fn render_environment(out: &mut String, report: &Report) {
    out.push_str("## Environment\n\n");
    let _ = writeln!(out, "Measured {}.\n", report.generated_at);
    out.push_str("| | |\n| --- | --- |\n");
    let _ = writeln!(out, "| OS | {} |", md_cell(&report.host.os));
    let _ = writeln!(out, "| Kernel | {} |", md_cell(&report.host.kernel));
    let _ = writeln!(out, "| CPU | {} |", md_cell(&report.host.cpu));
    let _ = writeln!(out, "| Arch | {} |", md_cell(&report.host.arch));
    out.push('\n');

    out.push_str("Version strings are captured by executing each runtime.\nA runtime missing from this table was not installed on this host; it appears under [Not measured](#not-measured).\n\n");
    out.push_str("| Runtime | Version |\n| --- | --- |\n");
    for runtime in &report.runtimes {
        if runtime.outcome.bytes().is_none() {
            continue;
        }
        let _ = writeln!(
            out,
            "| `{}` | {} |",
            runtime.runtime,
            md_cell(runtime.version.as_deref().unwrap_or("unknown")),
        );
    }
    out.push('\n');
}

fn render_results(out: &mut String, report: &Report, charts: &[Chart]) {
    out.push_str("## Results\n\n");
    out.push_str("Raw bytes on disk, never compressed.\nEach figure is a log axis in bytes, smallest first, with its full numbers in the table below it.\n\n");
    render_runtimes(out, report, charts);
    render_apps(out, report, charts);
}

fn render_runtimes(out: &mut String, report: &Report, charts: &[Chart]) {
    if report
        .runtimes
        .iter()
        .all(|runtime| runtime.outcome.bytes().is_none())
    {
        return;
    }
    out.push_str("### Native runtimes\n\n");
    if let Some(chart) = charts.iter().find(|chart| chart.key == "runtimes") {
        render_chart(out, chart);
    }
    out.push_str("| Runtime | Size |\n| --- | --- |\n");
    for runtime in &report.runtimes {
        if let Outcome::Ok { bytes } = &runtime.outcome {
            let _ = writeln!(out, "| `{}` | {} |", runtime.runtime, fmt_bytes(*bytes));
        }
    }
    out.push('\n');
}

fn render_apps(out: &mut String, report: &Report, charts: &[Chart]) {
    for app in &report.apps {
        let Outcome::Ok { bytes: wasm } = &app.wasm else {
            continue;
        };
        let _ = writeln!(out, "### `{}`\n", app.file);
        if let Some(chart) = charts.iter().find(|chart| chart.key == app.app) {
            render_chart(out, chart);
        }
        out.push_str("| Target | Size |\n| --- | --- |\n");
        let _ = writeln!(out, "| wasm binary | {} |", fmt_bytes(*wasm));
        for cell in &app.targets {
            let size = match &cell.outcome {
                Outcome::Ok { bytes } => fmt_bytes(*bytes),
                Outcome::Skipped { .. } => "—".to_string(),
                Outcome::Failed { reason } => format!("**FAILED**: {}", md_cell(reason)),
            };
            let _ = writeln!(out, "| `{}` | {size} |", cell.target);
        }
        out.push('\n');
    }
}

/// Everything the command did not weigh, with the reason it gives: an uninstalled runtime, an app that is not in the cache.
/// Stated here rather than left as a gap in the tables above.
fn render_gaps(out: &mut String, report: &Report) {
    let mut gaps: Vec<(String, &str)> = Vec::new();
    for runtime in &report.runtimes {
        if let Outcome::Skipped { reason } | Outcome::Failed { reason } = &runtime.outcome {
            gaps.push((format!("runtime `{}`", runtime.runtime), reason));
        }
    }
    for app in &report.apps {
        if let Outcome::Skipped { reason } | Outcome::Failed { reason } = &app.wasm {
            gaps.push((format!("`{}`", app.file), reason));
            continue;
        }
        for cell in &app.targets {
            if let Outcome::Skipped { reason } = &cell.outcome {
                gaps.push((format!("`{}` → `{}`", app.file, cell.target), reason));
            }
        }
    }

    out.push_str("## Not measured\n\n");
    if gaps.is_empty() {
        out.push_str(
            "Nothing: every runtime in the matrix and every app in the corpus was weighed.\n",
        );
        return;
    }
    out.push_str("| Item | Reason |\n| --- | --- |\n");
    for (item, reason) in gaps {
        let _ = writeln!(out, "| {item} | {} |", md_cell(reason));
    }
    out.push('\n');
}

/// A chart, above the table it summarizes.
/// `<picture>` rather than a bare `<img>` because dark mode is a *selected* variant with its own file.
/// Paths are relative to `docs/sizes/results.md`, which sits beside the `figs/` directory the SVGs are written into.
fn render_chart(out: &mut String, chart: &Chart) {
    out.push_str("<picture>\n");
    let _ = writeln!(
        out,
        "  <source media=\"(prefers-color-scheme: dark)\" srcset=\"figs/{}-dark.svg\">",
        chart.stem
    );
    let _ = writeln!(
        out,
        "  <img alt=\"{}\" src=\"figs/{}.svg\">",
        html_attr(&chart.alt),
        chart.stem
    );
    out.push_str("</picture>\n\n");
}

/// A size at three significant figures with a decimal SI prefix: `214 kB`, `4.79 MB`.
/// Decimal, not binary: a release artifact's size is quoted in MB by every distribution channel there is.
/// Whole bytes below 1 kB, where a fraction would be a fiction.
pub fn fmt_bytes(bytes: u64) -> String {
    fmt_bytes_f(bytes as f64)
}

/// [`fmt_bytes`] on a float, for the chart axis, which works in `f64` throughout.
pub fn fmt_bytes_f(bytes: f64) -> String {
    let rounded = round3(bytes);
    let (scale, unit) = si_unit(rounded);
    let mantissa = rounded / scale;
    let decimals = if unit == "B" {
        0
    } else if mantissa < 10.0 {
        2
    } else if mantissa < 100.0 {
        1
    } else {
        0
    };
    format!("{mantissa:.decimals$} {unit}")
}

/// A power-of-ten gridline label: `1 kB`, `10 MB`.
/// Bare mantissa and unit, no decimals.
pub fn fmt_byte_tick(bytes: f64) -> String {
    let (scale, unit) = si_unit(bytes);
    format!("{:.0} {unit}", bytes / scale)
}

/// The SI prefix a size reads best in: the largest unit that still leaves a mantissa of at least 1.
/// The slack absorbs the float error in a power of ten, so a tick one ULP low is not labelled `1000 kB`.
fn si_unit(bytes: f64) -> (f64, &'static str) {
    const UNITS: [(f64, &str); 4] = [(1e9, "GB"), (1e6, "MB"), (1e3, "kB"), (1.0, "B")];
    UNITS
        .into_iter()
        .find(|(scale, _)| bytes >= scale * 0.999999)
        .unwrap_or((1.0, "B"))
}

/// Escape the one character that would break a markdown table row.
fn md_cell(text: &str) -> String {
    text.replace('|', "\\|")
}

/// Escape text going into a double-quoted HTML attribute (the chart alt text, which is generated).
fn html_attr(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
