// Command `nes` runs a converted NES emulator as pure Go.
// The `./nes` package is dewasm's conversion of `cache/nes.wasm`, which is built on `agnes`.
// That is `nes_gen.go`, regenerated by `build.sh`.
// It comes together with the Ebiten frontend that drives it.
//
// Run with `-smoke` for a headless self-check; see `./nes` for the frontend itself.
package main

import "nes-example/nes"

func main() {
	nes.Run()
}
