// Command nes runs a converted NES emulator as pure Go.
// The ./nes package is dewasm's conversion of the agnes-based cache/nes.wasm.
// That is nes_gen.go, regenerated by build.sh.
// It comes together with the ebiten frontend that drives it.
//
// Run with -smoke for a headless self-check; see ./nes for the frontend itself.
package main

import "nes-example/nes"

func main() {
	nes.Run()
}
