//! The module-name policy for Java: a dotted library name splits into a `package` declaration plus a verbatim class name, an invalid one is a conversion-time error, and standalone output ignores the name for a fixed `Program` (which is also its `argv[0]`, see docs/standalone-interface.md).

use std::process::Command;

use dewasm_backend::Mode;
use dewasm_backend_java::{find_java, javac_command, JavaBackend};

const ADD_WAT: &str = r#"(module
  (func (export "add") (param i32 i32) (result i32) (i32.add (local.get 0) (local.get 1))))"#;

// Keywords like `int` are NOT rejected: the grammar is character-level only, and javac is the authority on the rest.
dewasm_test_helper::module_name_policy_suite!(
    backend: JavaBackend,
    wat: ADD_WAT,
    invalid: ["sqlite3-shell", "", "com..Add", "3Add", "com.Add."],
    error_contains: "invalid java module name",
    standalone_markers: ["final class Program {"],
);

/// The whole point of the dotted form: a conventional package *and* a conventional class name, with the embedder's `Main` appended to the same compilation unit (docs/backends/java.md) and therefore the same package.
#[test]
fn dotted_name_emits_a_package_and_runs() {
    let source = convert("com.github.dewasm.Add", Mode::Library).expect("convert");
    assert!(
        source.starts_with("// Generated by dewasm. Do not edit.\npackage com.github.dewasm;\n"),
        "the package declaration must precede every type in the file, got:\n{}",
        &source[..source.len().min(120)]
    );
    assert!(source.contains("final class Add {"));

    let program = format!(
        "{source}\npublic class Main {{\n    \
         public static void main(String[] a) {{\n        \
         Add inst = new Add(null, null, null, null);\n        \
         System.out.println((int)(Integer)((Add.Rt.Fn) inst.Exports.get(\"add\")).invoke(new Object[]{{2, 3}}));\n    \
         }}\n}}\n"
    );

    let dir = std::env::temp_dir().join(format!("dewasm-java-module-name-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let src = dir.join("Main.java");
    std::fs::write(&src, &program).unwrap();
    let build = javac_command()
        .arg("-d")
        .arg(&dir)
        .arg(&src)
        .output()
        .expect("spawn javac");
    assert!(
        build.status.success(),
        "javac failed:\n{}",
        String::from_utf8_lossy(&build.stderr)
    );

    let java = find_java().expect("java not found on PATH (or $DEWASM_JAVA) — see docs/testing.md");
    let out = Command::new(&java)
        .arg("-cp")
        .arg(&dir)
        .arg("com.github.dewasm.Main")
        .output()
        .expect("spawn java");
    assert!(
        out.status.success(),
        "java failed: {}\n{}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );
    assert_eq!(String::from_utf8_lossy(&out.stdout), "5\n");
    let _ = std::fs::remove_dir_all(&dir);
}

/// An undotted name is the class name, with no package line.
#[test]
fn undotted_name_emits_no_package() {
    let source = convert("Add", Mode::Library).expect("convert");
    assert!(!source.contains("package "));
    assert!(source.contains("final class Add {"));
}

/// Standalone output carries no `package` line either, even from a name whose dots would have produced one in library mode: the fixed class is also the artifact's `argv[0]`, which a package would have qualified.
#[test]
fn standalone_emits_no_package() {
    let source = convert("com.github.dewasm.Add", Mode::Standalone).expect("convert");
    assert!(!source.contains("package "));
}
