[package]
name = "dewasmify-backend-ruby"
description = "Ruby backend for dewasmify"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
dewasmify-core.workspace = true
dewasmify-backend.workspace = true

[dev-dependencies]
regex.workspace = true
