//! Ruby backend: translates dewasmify IR into a Ruby class plus an embedded
//! lightweight runtime.
//!
//! Lowering conventions (shared with the runtime in runtime/ruby/):
//! - i32/i64 are unsigned (masked) Ruby Integers; signed views via
//!   `Dewasmify.s32/s64` only where an instruction needs them.
//! - f32/f64 are Ruby Floats; f32 results are re-rounded with
//!   `Dewasmify.f32`.
//! - Multi-level `br` uses catch/throw; loops become `while true` with a
//!   catch whose value distinguishes continue (throw) from fallthrough.

use anyhow::Result;
use dewasmify_backend::{Backend, CodeWriter, GenOptions, Mode, OutputFile};
use dewasmify_core::ir::{
    BinOp, BrTarget, Expr, ExportKind, LoadOp, Module, Stmt, StoreOp, Temp, UnOp, ValType,
};

const RUNTIME_RB: &str = include_str!("../../../runtime/ruby/runtime.rb");
const WASI_RB: &str = include_str!("../../../runtime/ruby/wasi.rb");

/// The embedded runtime source (for embedders that emit several classes
/// into one file, like the spec test harness).
pub fn runtime_source() -> &'static str {
    RUNTIME_RB
}

/// Generate only the class definition for a module, without the runtime
/// prelude.
pub fn generate_class(module: &Module, class_name: &str) -> String {
    let mut w = CodeWriter::new("  ");
    Gen { module }.class(&mut w, class_name);
    w.finish()
}

pub struct RubyBackend;

impl Backend for RubyBackend {
    fn name(&self) -> &str {
        "ruby"
    }

    fn file_extension(&self) -> &str {
        "rb"
    }

    fn generate(&self, module: &Module, opts: &GenOptions) -> Result<Vec<OutputFile>> {
        let class_name = class_name(&opts.module_name);
        let mut w = CodeWriter::new("  ");

        w.line("# Generated by dewasmify. Do not edit.");
        w.line("# frozen_string_literal: false");
        w.line("");
        w.raw(RUNTIME_RB);
        w.line("");
        if opts.mode == Mode::Standalone {
            w.raw(WASI_RB);
            w.line("");
        }

        let gen = Gen { module };
        gen.class(&mut w, &class_name);

        if opts.mode == Mode::Standalone {
            w.line("");
            w.block("if __FILE__ == $PROGRAM_NAME", "end", |w| {
                w.line("wasi = Dewasmify::WASI.new(args: [File.basename($PROGRAM_NAME), *ARGV], env: ENV.to_h)");
                w.line(format!("inst = {class_name}.new(wasi.imports)"));
                w.line("wasi.memory = inst.memory");
                w.block("begin", "end", |w| {
                    w.line("inst.invoke(\"_start\")");
                    w.line("exit 0");
                    w.line("rescue Dewasmify::Exit => e");
                    w.line("  exit e.code");
                    w.line("rescue Dewasmify::Trap => e");
                    w.line("  warn \"trap: #{e.message}\"");
                    w.line("  exit 134");
                });
            });
        }

        Ok(vec![OutputFile {
            name: format!("{}.rb", opts.module_name),
            contents: w.finish(),
        }])
    }
}

fn class_name(module_name: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in module_name.chars() {
        if c.is_ascii_alphanumeric() {
            if upper {
                out.extend(c.to_uppercase());
                upper = false;
            } else {
                out.push(c);
            }
        } else {
            upper = true;
        }
    }
    if out.is_empty() || out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert_str(0, "Wasm");
    }
    out
}

fn ruby_string(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '#' => out.push_str("\\#"),
            c if (c as u32) < 0x20 || (c as u32) == 0x7f => {
                out.push_str(&format!("\\u{{{:x}}}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn hex_bytes(data: &[u8]) -> String {
    let mut hex = String::with_capacity(data.len() * 2);
    for b in data {
        hex.push_str(&format!("{b:02x}"));
    }
    format!("[\"{hex}\"].pack(\"H*\")")
}

struct Gen<'a> {
    module: &'a Module,
}

impl<'a> Gen<'a> {
    fn class(&self, w: &mut CodeWriter, class_name: &str) {
        w.block(format!("class {class_name}"), "end", |w| {
            self.initialize(w);
            w.line("");
            w.line("attr_reader :memory, :exports");
            w.line("");
            w.block("def invoke(name, *args)", "end", |w| {
                w.line("@exports.fetch(name).call(*args)");
            });
            w.line("");
            w.block("def global_get(name)", "end", |w| {
                w.line("instance_variable_get(GLOBAL_EXPORTS.fetch(name))");
            });
            w.line("");
            w.line("private");
            for (i, func) in self.module.funcs.iter().enumerate() {
                w.line("");
                let idx = self.module.num_imported_funcs() as usize + i;
                self.function(w, idx as u32, func);
            }
        });
    }

    fn initialize(&self, w: &mut CodeWriter) {
        let m = self.module;

        let mut global_exports: Vec<(String, u32)> = Vec::new();
        for export in &m.exports {
            if let ExportKind::Global(idx) = export.kind {
                global_exports.push((export.name.clone(), idx));
            }
        }
        let entries = global_exports
            .iter()
            .map(|(name, idx)| format!("{} => :@g{}", ruby_string(name), idx))
            .collect::<Vec<_>>()
            .join(", ");
        w.line(format!("GLOBAL_EXPORTS = {{ {entries} }}.freeze"));
        w.line("");

        w.block("def initialize(imports = {})", "end", |w| {
            if let Some(mem) = &m.memory {
                let max = mem
                    .max_pages
                    .map(|p| p.to_string())
                    .unwrap_or_else(|| "nil".to_string());
                w.line(format!(
                    "@memory = Dewasmify::Memory.new({}, {})",
                    mem.min_pages, max
                ));
            }
            if let Some(table) = &m.table {
                w.line(format!("@table = Dewasmify::Table.new({})", table.min));
            }
            for (i, import) in m.imported_funcs.iter().enumerate() {
                w.line(format!(
                    "@if{i} = imports.dig({}, {}) || raise(ArgumentError, {})",
                    ruby_string(&import.module),
                    ruby_string(&import.name),
                    ruby_string(&format!(
                        "missing import {}.{}",
                        import.module, import.name
                    )),
                ));
            }
            for (i, global) in m.globals.iter().enumerate() {
                w.line(format!("@g{} = {}", i, self.expr(&global.init)));
            }
            for elem in &m.elems {
                let offset = self.expr(&elem.offset);
                w.line(format!(
                    "@table.check_range({offset}, {})",
                    elem.func_indices.len()
                ));
                for (i, func_idx) in elem.func_indices.iter().enumerate() {
                    let ty = self.func_type_idx(*func_idx);
                    w.line(format!(
                        "@table.set({offset} + {i}, {ty}, {})",
                        self.func_ref(*func_idx)
                    ));
                }
            }
            for (i, data) in m.datas.iter().enumerate() {
                match &data.offset {
                    Some(offset) => {
                        w.line(format!(
                            "@memory.init({}, {}, 0, {})",
                            self.expr(offset),
                            hex_bytes(&data.data),
                            data.data.len()
                        ));
                        w.line(format!("@data{i} = \"\".b"));
                    }
                    None => {
                        w.line(format!("@data{i} = {}", hex_bytes(&data.data)));
                    }
                }
            }

            let mut export_entries = Vec::new();
            for export in &m.exports {
                if let ExportKind::Func(idx) = export.kind {
                    export_entries
                        .push(format!("{} => {}", ruby_string(&export.name), self.func_ref(idx)));
                }
            }
            w.line(format!("@exports = {{ {} }}", export_entries.join(", ")));

            if let Some(start) = m.start {
                w.line(self.call_string(start, &[]));
            }
        });
    }

    fn func_type_idx(&self, func_idx: u32) -> u32 {
        let idx = func_idx as usize;
        let imports = self.module.imported_funcs.len();
        let ty = if idx < imports {
            self.module.imported_funcs[idx].type_idx
        } else {
            self.module.funcs[idx - imports].type_idx
        };
        self.canonical_type(ty)
    }

    /// call_indirect compares types structurally, so identical function
    /// types declared at different indices must collapse to one id.
    fn canonical_type(&self, type_idx: u32) -> u32 {
        let ty = &self.module.types[type_idx as usize];
        self.module
            .types
            .iter()
            .position(|t| t == ty)
            .map(|i| i as u32)
            .unwrap_or(type_idx)
    }

    /// A callable object for the function (used in tables and exports).
    fn func_ref(&self, func_idx: u32) -> String {
        if (func_idx as usize) < self.module.imported_funcs.len() {
            format!("@if{func_idx}")
        } else {
            format!("method(:_f{func_idx})")
        }
    }

    fn call_string(&self, func_idx: u32, args: &[String]) -> String {
        let args = args.join(", ");
        if (func_idx as usize) < self.module.imported_funcs.len() {
            format!("@if{func_idx}.call({args})")
        } else if args.is_empty() {
            format!("_f{func_idx}")
        } else {
            format!("_f{func_idx}({args})")
        }
    }

    fn function(&self, w: &mut CodeWriter, idx: u32, func: &dewasmify_core::ir::Func) {
        let ty = &self.module.types[func.type_idx as usize];
        let params = (0..ty.params.len())
            .map(|i| format!("l{i}"))
            .collect::<Vec<_>>()
            .join(", ");
        let header = if params.is_empty() {
            format!("def _f{idx}")
        } else {
            format!("def _f{idx}({params})")
        };
        w.block(header, "end", |w| {
            for (i, local_ty) in func.locals.iter().enumerate() {
                let name = format!("l{}", ty.params.len() + i);
                w.line(format!("{name} = {}", default_value(*local_ty)));
            }
            // Hoist all temps to method scope: assignments inside catch/do
            // blocks would otherwise be block-local in Ruby.
            let mut depths: Vec<u32> = func.temps.iter().map(|t| t.depth).collect();
            depths.dedup();
            if !depths.is_empty() {
                let decl = depths
                    .iter()
                    .map(|d| format!("s{d} = "))
                    .collect::<String>();
                w.line(format!("{decl}nil"));
            }
            self.stmts(w, &func.body);
        });
    }

    fn stmts(&self, w: &mut CodeWriter, stmts: &[Stmt]) {
        for stmt in stmts {
            self.stmt(w, stmt);
        }
    }

    fn stmt(&self, w: &mut CodeWriter, stmt: &Stmt) {
        match stmt {
            Stmt::Assign { dst, expr } => {
                w.line(format!("{} = {}", temp(*dst), self.expr(expr)));
            }
            Stmt::LocalSet { idx, expr } => {
                w.line(format!("l{idx} = {}", self.expr(expr)));
            }
            Stmt::GlobalSet { idx, expr } => {
                w.line(format!("@g{idx} = {}", self.expr(expr)));
            }
            Stmt::Store { op, addr, value, offset } => {
                w.line(format!(
                    "@memory.{}({}, {})",
                    store_method(*op),
                    self.addr(addr, *offset),
                    self.expr(value)
                ));
            }
            Stmt::Block { label, body } => {
                w.block(format!("catch(:l{}) do", label.id), "end", |w| {
                    self.stmts(w, body);
                });
            }
            Stmt::Loop { label, body } => {
                w.block("while true", "end", |w| {
                    w.block(format!("__b = catch(:l{}) do", label.id), "end", |w| {
                        self.stmts(w, body);
                        w.line("true");
                    });
                    w.line("break if __b");
                });
            }
            Stmt::If { label, cond, then, els } => {
                let emit_if = |w: &mut CodeWriter, gen: &Self| {
                    w.line(format!("if {} != 0", gen.expr(cond)));
                    w.indent();
                    if then.is_empty() {
                        w.line("nil");
                    } else {
                        gen.stmts(w, then);
                    }
                    w.dedent();
                    if !els.is_empty() {
                        w.line("else");
                        w.indent();
                        gen.stmts(w, els);
                        w.dedent();
                    }
                    w.line("end");
                };
                if label.referenced {
                    w.block(format!("catch(:l{}) do", label.id), "end", |w| {
                        emit_if(w, self);
                    });
                } else {
                    emit_if(w, self);
                }
            }
            Stmt::Br(target) => self.branch(w, target),
            Stmt::BrIf { cond, target } => {
                w.block(format!("if {} != 0", self.expr(cond)), "end", |w| {
                    self.branch(w, target);
                });
            }
            Stmt::BrTable { index, targets, default } => {
                if targets.is_empty() {
                    self.branch(w, default);
                    return;
                }
                w.line(format!("case {}", self.expr(index)));
                for (i, target) in targets.iter().enumerate() {
                    w.line(format!("when {i}"));
                    w.indent();
                    self.branch(w, target);
                    w.dedent();
                }
                w.line("else");
                w.indent();
                self.branch(w, default);
                w.dedent();
                w.line("end");
            }
            Stmt::Return { values } => self.return_stmt(w, values),
            Stmt::Call { func, args, results } => {
                let args: Vec<String> = args.iter().map(|a| self.expr(a)).collect();
                let call = self.call_string(*func, &args);
                w.line(assign_results(results, call));
            }
            Stmt::CallIndirect { type_idx, index, args, results } => {
                let mut call_args =
                    vec![self.expr(index), self.canonical_type(*type_idx).to_string()];
                call_args.extend(args.iter().map(|a| self.expr(a)));
                let call = format!("@table.call({})", call_args.join(", "));
                w.line(assign_results(results, call));
            }
            Stmt::MemoryGrow { dst, delta } => {
                w.line(format!("{} = @memory.grow({})", temp(*dst), self.expr(delta)));
            }
            Stmt::MemoryCopy { dst, src, len } => {
                w.line(format!(
                    "@memory.copy({}, {}, {})",
                    self.expr(dst),
                    self.expr(src),
                    self.expr(len)
                ));
            }
            Stmt::MemoryFill { dst, val, len } => {
                w.line(format!(
                    "@memory.fill({}, {}, {})",
                    self.expr(dst),
                    self.expr(val),
                    self.expr(len)
                ));
            }
            Stmt::MemoryInit { seg, dst, src, len } => {
                w.line(format!(
                    "@memory.init({}, @data{seg}, {}, {})",
                    self.expr(dst),
                    self.expr(src),
                    self.expr(len)
                ));
            }
            Stmt::DataDrop { seg } => {
                w.line(format!("@data{seg} = \"\".b"));
            }
            Stmt::Unreachable => {
                w.line("Dewasmify.trap(\"unreachable\")");
            }
        }
    }

    fn return_stmt(&self, w: &mut CodeWriter, values: &[Expr]) {
        match values {
            [] => w.line("return"),
            [v] => w.line(format!("return {}", self.expr(v))),
            vs => {
                let vs = vs.iter().map(|v| self.expr(v)).collect::<Vec<_>>().join(", ");
                w.line(format!("return [{vs}]"));
            }
        }
    }

    fn branch(&self, w: &mut CodeWriter, target: &BrTarget) {
        match target {
            BrTarget::Return { values } => self.return_stmt(w, values),
            BrTarget::Label { label, is_loop, assigns } => {
                for (dst, src) in assigns {
                    w.line(format!("{} = {}", temp(*dst), temp(*src)));
                }
                if *is_loop {
                    w.line(format!("throw :l{label}, false"));
                } else {
                    w.line(format!("throw :l{label}"));
                }
            }
        }
    }

    fn addr(&self, addr: &Expr, offset: u64) -> String {
        if offset == 0 {
            self.expr(addr)
        } else {
            format!("{} + {offset}", self.expr(addr))
        }
    }

    fn expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::I32Const(v) => v.to_string(),
            Expr::I64Const(v) => v.to_string(),
            Expr::F32Const(bits) => {
                let v = f32::from_bits(*bits);
                if v.is_finite() {
                    format!("{:?}", v as f64)
                } else {
                    format!("Dewasmify.f32_from_bits(0x{bits:x})")
                }
            }
            Expr::F64Const(bits) => {
                let v = f64::from_bits(*bits);
                if v.is_finite() {
                    format!("{v:?}")
                } else {
                    format!("Dewasmify.f64_from_bits(0x{bits:x})")
                }
            }
            Expr::Temp(t) => temp(*t),
            Expr::LocalGet(idx) => format!("l{idx}"),
            Expr::GlobalGet(idx) => format!("@g{idx}"),
            Expr::Un(op, a) => self.un(*op, &self.expr(a)),
            Expr::Bin(op, a, b) => self.bin(*op, &self.expr(a), &self.expr(b)),
            Expr::Load { op, addr, offset } => {
                format!("@memory.{}({})", load_method(*op), self.addr(addr, *offset))
            }
            Expr::Select { cond, then, els } => {
                format!(
                    "({} != 0 ? {} : {})",
                    self.expr(cond),
                    self.expr(then),
                    self.expr(els)
                )
            }
            Expr::MemorySize => "@memory.size".to_string(),
        }
    }

    fn un(&self, op: UnOp, a: &str) -> String {
        use UnOp::*;
        match op {
            I32Eqz | I64Eqz => format!("({a} == 0 ? 1 : 0)"),
            I32Clz => format!("Dewasmify.i32_clz({a})"),
            I32Ctz => format!("Dewasmify.i32_ctz({a})"),
            I64Clz => format!("Dewasmify.i64_clz({a})"),
            I64Ctz => format!("Dewasmify.i64_ctz({a})"),
            I32Popcnt | I64Popcnt => format!("Dewasmify.popcnt({a})"),
            F32Abs => format!("Dewasmify.f32_abs({a})"),
            F32Neg => format!("Dewasmify.f32_neg({a})"),
            F64Abs => format!("Dewasmify.f64_abs({a})"),
            F64Neg => format!("Dewasmify.f64_neg({a})"),
            F32Ceil | F64Ceil => format!("Dewasmify.fceil({a})"),
            F32Floor | F64Floor => format!("Dewasmify.ffloor({a})"),
            F32Trunc | F64Trunc => format!("Dewasmify.ftrunc({a})"),
            F32Nearest | F64Nearest => format!("Dewasmify.fnearest({a})"),
            F32Sqrt => format!("Dewasmify.f32(Dewasmify.fsqrt({a}))"),
            F64Sqrt => format!("Dewasmify.fsqrt({a})"),
            I32WrapI64 => format!("({a} & 0xffffffff)"),
            I32TruncF32S | I32TruncF64S => format!("Dewasmify.i32_trunc_s({a})"),
            I32TruncF32U | I32TruncF64U => format!("Dewasmify.i32_trunc_u({a})"),
            I64TruncF32S | I64TruncF64S => format!("Dewasmify.i64_trunc_s({a})"),
            I64TruncF32U | I64TruncF64U => format!("Dewasmify.i64_trunc_u({a})"),
            I32TruncSatF32S | I32TruncSatF64S => format!("Dewasmify.i32_trunc_sat_s({a})"),
            I32TruncSatF32U | I32TruncSatF64U => format!("Dewasmify.i32_trunc_sat_u({a})"),
            I64TruncSatF32S | I64TruncSatF64S => format!("Dewasmify.i64_trunc_sat_s({a})"),
            I64TruncSatF32U | I64TruncSatF64U => format!("Dewasmify.i64_trunc_sat_u({a})"),
            I64ExtendI32S => format!("Dewasmify.i64_extend_i32_s({a})"),
            I64ExtendI32U => a.to_string(),
            F32ConvertI32S => format!("Dewasmify.f32(Dewasmify.s32({a}).to_f)"),
            F32ConvertI32U => format!("Dewasmify.f32({a}.to_f)"),
            F32ConvertI64S => format!("Dewasmify.cvt_f32_i(Dewasmify.s64({a}))"),
            F32ConvertI64U => format!("Dewasmify.cvt_f32_i({a})"),
            F64ConvertI32S => format!("Dewasmify.s32({a}).to_f"),
            F64ConvertI32U => format!("{a}.to_f"),
            F64ConvertI64S => format!("Dewasmify.cvt_f64_i(Dewasmify.s64({a}))"),
            F64ConvertI64U => format!("Dewasmify.cvt_f64_i({a})"),
            F32DemoteF64 => format!("Dewasmify.f32_demote({a})"),
            F64PromoteF32 => format!("Dewasmify.f64_promote({a})"),
            I32ReinterpretF32 => format!("Dewasmify.i32_reinterpret_f32({a})"),
            I64ReinterpretF64 => format!("Dewasmify.i64_reinterpret_f64({a})"),
            F32ReinterpretI32 => format!("Dewasmify.f32_reinterpret_i32({a})"),
            F64ReinterpretI64 => format!("Dewasmify.f64_reinterpret_i64({a})"),
            I32Extend8S => format!("Dewasmify.i32_extend8_s({a})"),
            I32Extend16S => format!("Dewasmify.i32_extend16_s({a})"),
            I64Extend8S => format!("Dewasmify.i64_extend8_s({a})"),
            I64Extend16S => format!("Dewasmify.i64_extend16_s({a})"),
            I64Extend32S => format!("Dewasmify.i64_extend32_s({a})"),
        }
    }

    fn bin(&self, op: BinOp, a: &str, b: &str) -> String {
        use BinOp::*;
        match op {
            I32Add => format!("(({a} + {b}) & 0xffffffff)"),
            I32Sub => format!("(({a} - {b}) & 0xffffffff)"),
            I32Mul => format!("(({a} * {b}) & 0xffffffff)"),
            I64Add => format!("(({a} + {b}) & 0xffffffffffffffff)"),
            I64Sub => format!("(({a} - {b}) & 0xffffffffffffffff)"),
            I64Mul => format!("(({a} * {b}) & 0xffffffffffffffff)"),
            I32DivS => format!("Dewasmify.i32_div_s({a}, {b})"),
            I32DivU => format!("Dewasmify.i32_div_u({a}, {b})"),
            I32RemS => format!("Dewasmify.i32_rem_s({a}, {b})"),
            I32RemU => format!("Dewasmify.i32_rem_u({a}, {b})"),
            I64DivS => format!("Dewasmify.i64_div_s({a}, {b})"),
            I64DivU => format!("Dewasmify.i64_div_u({a}, {b})"),
            I64RemS => format!("Dewasmify.i64_rem_s({a}, {b})"),
            I64RemU => format!("Dewasmify.i64_rem_u({a}, {b})"),
            I32And | I64And => format!("({a} & {b})"),
            I32Or | I64Or => format!("({a} | {b})"),
            I32Xor | I64Xor => format!("({a} ^ {b})"),
            I32Shl => format!("(({a} << ({b} & 31)) & 0xffffffff)"),
            I32ShrU => format!("({a} >> ({b} & 31))"),
            I32ShrS => format!("((Dewasmify.s32({a}) >> ({b} & 31)) & 0xffffffff)"),
            I64Shl => format!("(({a} << ({b} & 63)) & 0xffffffffffffffff)"),
            I64ShrU => format!("({a} >> ({b} & 63))"),
            I64ShrS => format!("((Dewasmify.s64({a}) >> ({b} & 63)) & 0xffffffffffffffff)"),
            I32Rotl => format!("Dewasmify.i32_rotl({a}, {b})"),
            I32Rotr => format!("Dewasmify.i32_rotr({a}, {b})"),
            I64Rotl => format!("Dewasmify.i64_rotl({a}, {b})"),
            I64Rotr => format!("Dewasmify.i64_rotr({a}, {b})"),
            I32Eq | I64Eq => format!("({a} == {b} ? 1 : 0)"),
            I32Ne | I64Ne => format!("({a} != {b} ? 1 : 0)"),
            I32LtU | I64LtU => format!("({a} < {b} ? 1 : 0)"),
            I32GtU | I64GtU => format!("({a} > {b} ? 1 : 0)"),
            I32LeU | I64LeU => format!("({a} <= {b} ? 1 : 0)"),
            I32GeU | I64GeU => format!("({a} >= {b} ? 1 : 0)"),
            I32LtS => format!("(Dewasmify.s32({a}) < Dewasmify.s32({b}) ? 1 : 0)"),
            I32GtS => format!("(Dewasmify.s32({a}) > Dewasmify.s32({b}) ? 1 : 0)"),
            I32LeS => format!("(Dewasmify.s32({a}) <= Dewasmify.s32({b}) ? 1 : 0)"),
            I32GeS => format!("(Dewasmify.s32({a}) >= Dewasmify.s32({b}) ? 1 : 0)"),
            I64LtS => format!("(Dewasmify.s64({a}) < Dewasmify.s64({b}) ? 1 : 0)"),
            I64GtS => format!("(Dewasmify.s64({a}) > Dewasmify.s64({b}) ? 1 : 0)"),
            I64LeS => format!("(Dewasmify.s64({a}) <= Dewasmify.s64({b}) ? 1 : 0)"),
            I64GeS => format!("(Dewasmify.s64({a}) >= Dewasmify.s64({b}) ? 1 : 0)"),
            F32Add => format!("Dewasmify.f32({a} + {b})"),
            F32Sub => format!("Dewasmify.f32({a} - {b})"),
            F32Mul => format!("Dewasmify.f32({a} * {b})"),
            F32Div => format!("Dewasmify.f32({a} / {b})"),
            F64Add => format!("({a} + {b})"),
            F64Sub => format!("({a} - {b})"),
            F64Mul => format!("({a} * {b})"),
            F64Div => format!("({a} / {b})"),
            F32Min | F64Min => format!("Dewasmify.fmin({a}, {b})"),
            F32Max | F64Max => format!("Dewasmify.fmax({a}, {b})"),
            F32Copysign => format!("Dewasmify.f32_copysign({a}, {b})"),
            F64Copysign => format!("Dewasmify.f64_copysign({a}, {b})"),
            F32Eq | F64Eq => format!("({a} == {b} ? 1 : 0)"),
            F32Ne | F64Ne => format!("({a} != {b} ? 1 : 0)"),
            F32Lt | F64Lt => format!("({a} < {b} ? 1 : 0)"),
            F32Gt | F64Gt => format!("({a} > {b} ? 1 : 0)"),
            F32Le | F64Le => format!("({a} <= {b} ? 1 : 0)"),
            F32Ge | F64Ge => format!("({a} >= {b} ? 1 : 0)"),
        }
    }
}

fn temp(t: Temp) -> String {
    format!("s{}", t.depth)
}

fn default_value(ty: ValType) -> &'static str {
    match ty {
        ValType::I32 | ValType::I64 => "0",
        ValType::F32 | ValType::F64 => "0.0",
    }
}

fn assign_results(results: &[Temp], call: String) -> String {
    match results {
        [] => call,
        [r] => format!("{} = {}", temp(*r), call),
        rs => {
            let names = rs.iter().map(|r| temp(*r)).collect::<Vec<_>>().join(", ");
            format!("{names} = {call}")
        }
    }
}

fn load_method(op: LoadOp) -> &'static str {
    use LoadOp::*;
    match op {
        I32Load => "i32_load",
        I64Load => "i64_load",
        F32Load => "f32_load",
        F64Load => "f64_load",
        I32Load8S => "i32_load8_s",
        I32Load8U => "i32_load8_u",
        I32Load16S => "i32_load16_s",
        I32Load16U => "i32_load16_u",
        I64Load8S => "i64_load8_s",
        I64Load8U => "i64_load8_u",
        I64Load16S => "i64_load16_s",
        I64Load16U => "i64_load16_u",
        I64Load32S => "i64_load32_s",
        I64Load32U => "i64_load32_u",
    }
}

fn store_method(op: StoreOp) -> &'static str {
    use StoreOp::*;
    match op {
        I32Store => "i32_store",
        I64Store => "i64_store",
        F32Store => "f32_store",
        F64Store => "f64_store",
        I32Store8 => "i32_store8",
        I32Store16 => "i32_store16",
        I64Store8 => "i64_store8",
        I64Store16 => "i64_store16",
        I64Store32 => "i64_store32",
    }
}
