//! The two outputs of `cargo xtask bench`: the machine-readable result file under `benchmarks/results/` and the generated `docs/benchmarks.md`.
//!
//! Timings are not reproducible byte-for-byte, so neither output is a compared snapshot and no freshness test guards them — unlike `docs/support.md` (`cargo xtask update-support-docs`) or the execution snapshots (ADR-56). The JSON is the record: host, every runtime's version string *as captured by executing it*, the date, and every sample. The markdown is a rendering of that same record, and it is required to state the losses as plainly as the wins.

use std::fmt::Write as _;

use serde::Serialize;

/// The full result record. `schema` exists so a later reader can tell an old drop from a new one.
#[derive(Serialize)]
pub struct Report {
    pub schema: u32,
    /// UTC, `YYYY-MM-DDTHH:MM:SSZ`.
    pub generated_at: String,
    pub host: Host,
    pub settings: Settings,
    /// Every runner in the matrix, available or not, in matrix order.
    pub runtimes: Vec<Runtime>,
    pub results: Vec<Cell>,
}

#[derive(Serialize)]
pub struct Host {
    pub os: String,
    pub arch: String,
    pub kernel: String,
    pub cpu: String,
}

#[derive(Serialize)]
pub struct Settings {
    pub reps: usize,
    pub target_ms: u64,
    pub timeout_s: u64,
    pub filter: Option<String>,
}

#[derive(Serialize)]
pub struct Runtime {
    pub runner: String,
    pub available: bool,
    /// Why not, when `available` is false. Phrased as the setup step that would fix it.
    pub unavailable_reason: Option<String>,
    /// Captured by running the runtime, not hardcoded.
    pub version: Option<String>,
}

#[derive(Serialize)]
pub struct Cell {
    pub workload: String,
    pub runner: String,
    #[serde(flatten)]
    pub outcome: Outcome,
}

#[derive(Serialize)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum Outcome {
    /// Measured.
    Ok(Measurement),
    /// Deliberately not run (unavailable runner, unbuilt module, declared exclusion). Always reported, never silently dropped.
    Skipped { reason: String },
    /// Attempted and broke. A stdout mismatch against wasmtime lands here too — a wrong answer is a hard failure, not a slow pass.
    Failed { reason: String },
}

#[derive(Serialize)]
pub struct Measurement {
    /// The calibrated `<iterations>`; `null` for an app workload, which has no iteration parameter.
    pub iterations: Option<u64>,
    pub reps: usize,
    /// `t(0)`: the `<iterations> = 0` run (or, for an app, its declared do-nothing variant). This *is* the cold-start metric — process startup plus module load — and it is what gets subtracted from `t(N)`.
    pub cold_start: Option<Samples>,
    /// `t(N)`: the full run.
    pub total: Samples,
    /// `t(N) - t(0)` on the minima. `null` when there is no `t(0)` to subtract, or when the difference came out non-positive (pure noise — the workload is too small to see on this runner).
    pub compute_s: Option<f64>,
    pub ns_per_op_min: Option<f64>,
    pub ns_per_op_median: Option<f64>,
    /// Module load/instantiate time as the third-party driver reports it on stderr (`load_ms=`). Only the pywasm/wardite runners produce this.
    pub load_ms: Option<f64>,
    pub verification: Verification,
}

#[derive(Serialize)]
pub struct Samples {
    pub min_s: f64,
    pub median_s: f64,
    pub samples_s: Vec<f64>,
}

#[derive(Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Verification {
    /// This runner *is* the reference (wasmtime).
    Reference,
    /// stdout was byte-identical to wasmtime's at the same iteration count. A mismatch never reaches here — it is an [`Outcome::Failed`].
    Match,
}

impl Report {
    /// Pretty-printed JSON, newline-terminated.
    pub fn to_json(&self) -> anyhow::Result<String> {
        let mut text = serde_json::to_string_pretty(self)?;
        text.push('\n');
        Ok(text)
    }
}

/// Render `docs/benchmarks.md`: the house style of `docs/related-work.md` and `docs/backends/*.md` — no front matter, plain `##` headings, markdown tables, inline ADR links — plus the generated-file marker `docs/support.md` carries.
pub fn render_doc(report: &Report) -> String {
    let mut out = String::new();
    out.push_str("# Benchmarks\n\n");
    out.push_str("<!-- AUTO-GENERATED by `cargo xtask bench`; do not edit by hand. Unlike docs/support.md there is no freshness test: timings are not reproducible byte-for-byte, so this file is a dated measurement, not a compared snapshot. -->\n\n");

    let _ = writeln!(
        out,
        "How fast is a wasm program after dewasm has turned it into Ruby, Python, Perl, Go, Java, or Bash source? This page is the measured answer, regenerated by `cargo xtask bench`. It is a *dated* answer: the numbers below were taken on one host on one day, and the section headers say which."
    );
    out.push('\n');

    render_environment(&mut out, report);
    render_method(&mut out);
    render_results(&mut out, report);
    render_gaps(&mut out, report);
    render_caveats(&mut out);
    out
}

fn render_environment(out: &mut String, report: &Report) {
    out.push_str("## Environment\n\n");
    let _ = writeln!(out, "Measured {}.\n", report.generated_at);
    out.push_str("| | |\n| --- | --- |\n");
    let _ = writeln!(out, "| OS | {} |", md_cell(&report.host.os));
    let _ = writeln!(out, "| Kernel | {} |", md_cell(&report.host.kernel));
    let _ = writeln!(out, "| CPU | {} |", md_cell(&report.host.cpu));
    let _ = writeln!(out, "| Arch | {} |", md_cell(&report.host.arch));
    let _ = writeln!(
        out,
        "| Repetitions | {} timed runs after one warmup |",
        report.settings.reps
    );
    let _ = writeln!(
        out,
        "| Calibration target | {} ms of compute per sample |",
        report.settings.target_ms
    );
    out.push('\n');

    out.push_str("Every version string below was captured by executing the runtime, not copied from a lockfile.\n\n");
    out.push_str("| Runner | Version | Status |\n| --- | --- | --- |\n");
    for runtime in &report.runtimes {
        let label = &runtime.runner;
        let version = runtime.version.as_deref().unwrap_or("—");
        let status = if runtime.available {
            "available".to_string()
        } else {
            format!(
                "**unavailable** — {}",
                runtime.unavailable_reason.as_deref().unwrap_or("no reason")
            )
        };
        let _ = writeln!(
            out,
            "| `{label}` | {} | {} |",
            md_cell(version),
            md_cell(&status)
        );
    }
    out.push('\n');
}

fn render_method(out: &mut String) {
    out.push_str("## How this is measured\n\n");
    out.push_str("The runners in this suite span roughly three orders of magnitude, so a single fixed iteration count would be meaningless — it either measures nothing but process startup on wasmtime or takes minutes per sample on Bash. Four rules make the comparison honest:\n\n");
    out.push_str("1. **Per-runner iteration scaling.** Each kernel takes an `<iterations>` argument and each workload declares a ceiling; the harness calibrates every (workload, runner) pair up from a trivial count until one sample reaches the compute target. The headline number is therefore normalized throughput (ns/op), with the raw times printed beside it so nothing is hidden.\n");
    out.push_str("2. **The zero run is subtracted.** Every kernel also runs at `<iterations> = 0`, which does no work but still starts the process, loads the module, and prints a result line. That time is the **cold start** column; `t(N) - t(0)` is the compute time. This removes process startup and module load uniformly for every runner — they differ enormously (an empty Ruby is ~0.05 s; loading the generated Ruby for SQLite costs ~0.7 s before any work happens).\n");
    out.push_str("3. **Minimum and median.** One warmup run, then N timed runs; both the minimum (the least noise-contaminated estimate) and the median are reported, so a noisy host is visible rather than smoothed away.\n");
    out.push_str("4. **Every runner's stdout is diffed against wasmtime's** at the same iteration count. A mismatch is a hard failure recorded in this table, not a quietly fast wrong answer — exactly the class of bug the spec harness exists for ([ADR-3](adr/3-testing-strategy.md), [ADR-2](adr/2-numeric-semantics.md)).\n\n");
    out.push_str("A runner that is not installed, a module that has not been built, and a pair that is deliberately excluded are all listed under [Not measured](#not-measured) with a reason. A blank cell never means \"covered\".\n\n");
}

fn render_results(out: &mut String, report: &Report) {
    out.push_str("## Results\n\n");
    let workloads = ordered_workloads(report);
    for workload in workloads {
        let cells: Vec<&Cell> = report
            .results
            .iter()
            .filter(|cell| cell.workload == workload)
            .collect();
        if !cells
            .iter()
            .any(|cell| matches!(cell.outcome, Outcome::Ok(_)))
        {
            continue;
        }
        let _ = writeln!(out, "### `{workload}`\n");
        // The ratio column compares like with like: normalized throughput for a kernel, whole wall time for an app (which has no iteration parameter).
        let wasmtime_cell = cells.iter().find_map(|cell| match &cell.outcome {
            Outcome::Ok(m) if cell.runner == "wasmtime" => Some(m),
            _ => None,
        });
        let is_app = workload.starts_with("app/");
        let baseline = wasmtime_cell.and_then(|m| {
            if is_app {
                Some(m.total.min_s)
            } else {
                m.ns_per_op_min
            }
        });

        if is_app {
            out.push_str("| Runner | Wall time (min) | Wall time (median) | Cold start `t(0)` | Compute `t(N)-t(0)` | vs wasmtime | Load |\n");
            out.push_str("| --- | --- | --- | --- | --- | --- | --- |\n");
        } else {
            out.push_str("| Runner | Iterations | ns/op (min) | ns/op (median) | Cold start `t(0)` | Total `t(N)` | vs wasmtime | Load |\n");
            out.push_str("| --- | --- | --- | --- | --- | --- | --- | --- |\n");
        }
        for cell in &cells {
            match &cell.outcome {
                Outcome::Ok(m) => render_ok_row(out, cell, m, baseline, is_app),
                Outcome::Failed { reason } => {
                    let span = if is_app { 6 } else { 7 };
                    let _ = writeln!(
                        out,
                        "| `{}` |{} **FAILED** — {} |",
                        cell.runner,
                        " |".repeat(span - 1),
                        md_cell(reason)
                    );
                }
                Outcome::Skipped { .. } => {}
            }
        }
        out.push('\n');
    }
}

fn render_ok_row(
    out: &mut String,
    cell: &Cell,
    m: &Measurement,
    baseline: Option<f64>,
    is_app: bool,
) {
    let cold = m
        .cold_start
        .as_ref()
        .map_or_else(|| "—".to_string(), |s| fmt_seconds(s.min_s));
    let load = m
        .load_ms
        .map_or_else(|| "—".to_string(), |ms| format!("{ms:.1} ms"));
    let mine = if is_app {
        Some(m.total.min_s)
    } else {
        m.ns_per_op_min
    };
    let ratio = match (baseline, mine) {
        (Some(base), Some(mine)) if base > 0.0 => fmt_ratio(mine / base),
        _ => "—".to_string(),
    };
    if is_app {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} | {ratio} | {load} |",
            cell.runner,
            fmt_seconds(m.total.min_s),
            fmt_seconds(m.total.median_s),
            cold,
            m.compute_s.map_or_else(|| "—".to_string(), fmt_seconds),
        );
    } else {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} | {} | {ratio} | {load} |",
            cell.runner,
            m.iterations.map_or_else(|| "—".to_string(), fmt_count),
            m.ns_per_op_min.map_or_else(|| "—".to_string(), fmt_ns),
            m.ns_per_op_median.map_or_else(|| "—".to_string(), fmt_ns),
            cold,
            fmt_seconds(m.total.min_s),
        );
    }
}

fn render_gaps(out: &mut String, report: &Report) {
    out.push_str("## Not measured\n\n");
    let skipped: Vec<&Cell> = report
        .results
        .iter()
        .filter(|cell| matches!(cell.outcome, Outcome::Skipped { .. }))
        .collect();
    if skipped.is_empty() {
        out.push_str("Nothing: every (workload, runner) pair in the matrix was measured.\n\n");
        return;
    }
    out.push_str("Every pair the suite did not measure, and why. A missing runner or an unbuilt module is stated here rather than left as a gap in the tables above.\n\n");
    out.push_str("| Workload | Runner | Reason |\n| --- | --- | --- |\n");
    for cell in skipped {
        if let Outcome::Skipped { reason } = &cell.outcome {
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} |",
                cell.workload,
                cell.runner,
                md_cell(reason)
            );
        }
    }
    out.push('\n');
}

fn render_caveats(out: &mut String) {
    out.push_str("## What these numbers do not say\n\n");
    out.push_str("- **dewasm is not competitive with an AOT compiler, and is not trying to be.** wasmtime compiles to native code; every dewasm backend emits source for a host language and pays that language's interpretation cost on every wasm instruction. Bash is the extreme: it runs on the order of 1000x slower than wasmtime, because a shell has no integers-as-machine-words and no floats at all ([ADR-5](adr/5-bash-softfloat.md), [ADR-13](adr/13-bash-softfloat-conventions.md)).\n");
    out.push_str("- **We are not competitive with wasm2c or w2c2 either.** Those translate wasm to C, which a C compiler then optimizes to native code; the comparison that matters for dewasm is against *running wasm on the host language at all*, which is what the pywasm and wardite columns are ([related work](related-work.md)).\n");
    out.push_str("- **Interpreters legitimately beat us on cold start.** A wasm interpreter parses a module and starts executing; a dewasm backend hands the host language a large generated source file to parse first. The `app/sqlite3_cold_start` case exists to show that, not to hide it.\n");
    out.push_str("- **Iteration counts differ per runner by design.** Comparing raw wall times across rows is wrong; compare the ns/op column, and read the minimum against the median before trusting a small difference.\n");
    out.push_str("- **One host, one day.** Nothing here is a regression gate. There is no freshness test on this file precisely because a timing is not a snapshot.\n");
}

/// Workload labels in the order they first appear in `results`, which is the order the suite ran them.
fn ordered_workloads(report: &Report) -> Vec<String> {
    let mut seen: Vec<String> = Vec::new();
    for cell in &report.results {
        if !seen.contains(&cell.workload) {
            seen.push(cell.workload.clone());
        }
    }
    seen
}

fn fmt_seconds(seconds: f64) -> String {
    if seconds < 1.0 {
        format!("{:.1} ms", seconds * 1000.0)
    } else {
        format!("{seconds:.2} s")
    }
}

/// A slowdown factor against wasmtime. Sub-1.0 ratios (an interpreter winning on cold start) need a decimal to be readable at all.
fn fmt_ratio(ratio: f64) -> String {
    if ratio < 10.0 {
        format!("{ratio:.2}x")
    } else {
        format!("{ratio:.0}x")
    }
}

fn fmt_ns(ns: f64) -> String {
    if ns >= 1000.0 {
        format!("{ns:.0}")
    } else if ns >= 10.0 {
        format!("{ns:.1}")
    } else {
        format!("{ns:.2}")
    }
}

/// A thousands-separated iteration count, so a reader can tell 30000000 from 3000000 at a glance.
fn fmt_count(n: u64) -> String {
    let digits = n.to_string();
    let mut out = String::with_capacity(digits.len() + digits.len() / 3);
    for (i, ch) in digits.chars().enumerate() {
        if i > 0 && (digits.len() - i).is_multiple_of(3) {
            out.push(' ');
        }
        out.push(ch);
    }
    out
}

/// Escape the one character that would break a markdown table row.
fn md_cell(text: &str) -> String {
    text.replace('|', "\\|")
}
