#!/usr/bin/env bash
# Build the NES Java frontend: build the import-free nes.wasm reactor (agnes +
# our nes_demo.c, see examples/apps/scripts/nes.sh), run it through dewasm to
# regenerate the Nes.java library, then compile everything with plain javac.
# Nes.java is gitignored and regenerated by this script.
set -euo pipefail
cd "$(dirname "$0")"

script_dir="$(pwd)"
repo_root="$script_dir/../../.."

"$script_dir/../../apps/scripts/nes.sh"

(cd "$repo_root" && cargo run -q -p dewasm-cli -- \
  examples/apps/cache/nes.wasm --target java --mode library \
  --module-name Nes -o examples/nes/java/Nes.java)

mkdir -p classes
javac -d classes Main.java Nes.java

echo "build complete: classes/"
