#!/usr/bin/env bash
# Build the NES Java frontend.
# First build the import-free `nes.wasm` reactor (`agnes` + our `nes_demo.c`).
# `examples/apps/scripts/nes.sh` has the details.
# Then run it through dewasm to regenerate the `Nes.java` library.
# Then compile everything with plain `javac`.
# `Nes.java` is ignored by Git and regenerated by this script.
set -euo pipefail
cd "$(dirname "$0")"

script_dir="$(pwd)"
repo_root="$script_dir/../../.."

"$script_dir/../../apps/scripts/nes.sh"

(cd "$repo_root" && cargo run -q -p dewasm -- \
  examples/apps/cache/nes.wasm --target java --mode library \
  --module-name Nes -o examples/nes/java/Nes.java)

mkdir -p classes
javac -d classes Main.java Nes.java

echo "build complete: classes/"
