[package]
name = "dewasmify-backend-bash"
description = "Bash backend for dewasmify"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
dewasmify-core.workspace = true
dewasmify-backend.workspace = true

[dev-dependencies]
regex.workspace = true
