//! Bash backend: translates dewasm IR into a sourceable Bash script plus a bundled runtime of `<p>rt_*`/`<p>mem_*`/`<p>tab_*`/`<p>wasi_*` functions carrying the artifact's own prefix (ADR-62), so two generated scripts sourced into one shell never redefine each other's runtime.
//!
//! Lowering conventions (ADR-11; numeric conventions ADR-2):
//! - i32 is a masked-unsigned value in [0, 2^32); i64 is stored as its signed-64 two's-complement bit pattern (bash arithmetic is signed 64-bit only). Signed/unsigned views are derived inline.
//! - f32/f64 are their bit patterns (u32 / signed-64), computed by the pure-Bash softfloat units (ADR-5/ADR-13); reinterprets and float loads/stores are the identity over the integer paths.
//! - Structured control flow maps to `while :; do ...; break; done` wrappers; `br` becomes `break N`/`continue N` (bash counts only loops, `if` adds no level). Unreferenced labels emit no wrapper.
//! - Functions return values through the globals `R0, R1, ...`; traps set `TRAP_MSG` and propagate status 134 through `|| return $?` chains. Every generated function ends with an explicit `return 0` because a trailing arithmetic statement would leak status 1.
//! - One module instance per generation-time prefix: functions `<p>f<i>`, state `<p>g<i>`/`<p>mem`/`<p>t<i>` (per unified-index-space table), entry points `<p>init`, `<p>invoke`, `<p>global_get`, and — for `Embedded` linkage — the bundled runtime under the same prefix (`<p>rt_trap`, `<p>mem_i32_load`, ...). `TRAP_MSG`, `EXIT_CODE`, the `R0..` result registers and `IMPORTS`/`PROVIDERS` stay global: they are the calling protocol two artifacts must share to link at all (ADR-35/ADR-62). Imported functions resolve from the caller's `IMPORTS` array; other import kinds resolve through `PROVIDERS` + per-kind export maps, with imported globals and imported memory aliased in via `declare -gn` namerefs (ADR-35).
//!
//! Requires bash >= 5 (namerefs, associative arrays).

use std::cell::{Cell, RefCell};
use std::collections::BTreeSet;
use std::sync::OnceLock;

use anyhow::Result;
use dewasm_backend::{
    check_module_support, is_ident, module_name_error, Backend, CodeWriter, GenOptions, Mode,
    OutputFile, RuntimeBundler, RuntimeScope, SupportStatus,
};
use dewasm_core::feature::Feature;
use dewasm_core::ir::{
    BinOp, BrTarget, ElemItem, ElemKind, ExportKind, Expr, LoadOp, Module, Stmt, StoreOp, Temp,
    UnOp, ValType,
};

include!(concat!(env!("OUT_DIR"), "/units.rs"));

/// The runtime unit bundler for Bash (see runtime/bash/units/).
pub fn bundler() -> &'static RuntimeBundler {
    static BUNDLER: OnceLock<RuntimeBundler> = OnceLock::new();
    BUNDLER.get_or_init(|| {
        RuntimeBundler::new(
            "#",
            "\t",
            2,
            vec![
                RuntimeScope {
                    prefix: "rt",
                    open: "",
                    close: "",
                    prelude: Some("rt/_prelude"),
                },
                RuntimeScope {
                    prefix: "mem",
                    open: "",
                    close: "",
                    prelude: None,
                },
                RuntimeScope {
                    prefix: "wasi",
                    open: "",
                    close: "",
                    prelude: None,
                },
                RuntimeScope {
                    prefix: "tab",
                    open: "",
                    close: "",
                    prelude: None,
                },
            ],
            UNIT_SOURCES,
        )
        .expect("runtime units are well-formed")
    })
}

/// Emit a top-level shared runtime for the closure of `seeds`, under the flat unprefixed names (`rt_trap`, `mem_i32_load`, ...). This is the `Alias` shape: one runtime several modules generated by [`generate_module_with_units`] share, as the spec harness's `register` path does. `Embedded` output instead carries its own copy under its own prefix ([`prefix_runtime_names`], ADR-62).
pub fn shared_runtime(seeds: &BTreeSet<String>) -> Result<String> {
    bundler().bundle(seeds, 0)
}

/// Rewrite every runtime function name in a bundle to carry `prefix`, so the artifact's runtime is its own (ADR-62): `rt_trap` -> `<p>rt_trap`, `mem_i32_load` -> `<p>mem_i32_load`. A name is an identifier starting at a non-word character and beginning with one of the four unit scopes — the same grammar the units lint uses to find cross-unit references, which is what makes the rewrite complete. Definitions and call sites are both identifiers, so one pass over the text moves the whole runtime; a units lint keeps these names out of string literals, where a rewrite would change program-visible text. Applied to the bundle only, never to the generated module body (which can be hundreds of megabytes): its call sites are emitted with the prefix already in place.
pub fn prefix_runtime_names(bundle: &str, prefix: &str) -> String {
    let bytes = bundle.as_bytes();
    let is_word = |b: u8| b.is_ascii_alphanumeric() || b == b'_';
    let mut out = String::with_capacity(bundle.len());
    // Everything before `copied` is already in `out`; a match copies the run before it, then the prefix, and skips past the name.
    let mut copied = 0;
    let mut i = 0;
    while i < bytes.len() {
        let is_name_start = (i == 0 || !is_word(bytes[i - 1]))
            && [&b"rt_"[..], b"mem_", b"wasi_", b"tab_"]
                .iter()
                .any(|scope| bytes[i..].starts_with(scope));
        if !is_name_start {
            i += 1;
            continue;
        }
        out.push_str(&bundle[copied..i]);
        out.push_str(prefix);
        copied = i;
        i += bytes[i..]
            .iter()
            .position(|&b| !is_word(b))
            .unwrap_or(bytes.len() - i);
    }
    out.push_str(&bundle[copied..]);
    out
}

/// Locate a bash >= 5 interpreter able to run generated scripts: tries `$DEWASM_BASH`, then `bash` on PATH, then the common Homebrew/local install paths (macOS system bash is 3.2 and does not qualify).
pub fn find_bash5() -> Option<std::path::PathBuf> {
    static BASH: OnceLock<Option<std::path::PathBuf>> = OnceLock::new();
    BASH.get_or_init(find_bash5_uncached).clone()
}

/// The probe behind [`find_bash5`], memoized there: it spawns a process per candidate per call, and the interpreter cannot change under a running process.
fn find_bash5_uncached() -> Option<std::path::PathBuf> {
    use std::path::PathBuf;
    let mut candidates: Vec<PathBuf> = Vec::new();
    if let Ok(env) = std::env::var("DEWASM_BASH") {
        candidates.push(PathBuf::from(env));
    }
    candidates.push(PathBuf::from("bash"));
    candidates.push(PathBuf::from("/opt/homebrew/bin/bash"));
    candidates.push(PathBuf::from("/usr/local/bin/bash"));
    for candidate in candidates {
        let Ok(out) = std::process::Command::new(&candidate)
            .args(["-c", "echo ${BASH_VERSINFO[0]}"])
            .output()
        else {
            continue;
        };
        if String::from_utf8_lossy(&out.stdout)
            .trim()
            .parse::<u32>()
            .unwrap_or(0)
            >= 5
        {
            return Some(candidate);
        }
    }
    None
}

/// Generate one module for `module` with all names prefixed by `prefix` (e.g. `"m1_"`), calling the runtime under its flat unprefixed names — the `Alias` shape, paired with [`shared_runtime`]. Returns the source and the set of runtime units it needs; the caller decides whether to bundle them alongside.
pub fn generate_module_with_units(
    module: &Module,
    prefix: &str,
    default_wasi: bool,
) -> Result<(String, BTreeSet<String>)> {
    generate_module_inner(module, prefix, "", default_wasi, &BTreeSet::new())
}

/// `rt_prefix` is what every runtime call site is spelled with: empty for a shared flat runtime, the artifact's own prefix for `Embedded` output whose bundle went through [`prefix_runtime_names`].
fn generate_module_inner(
    module: &Module,
    prefix: &str,
    rt_prefix: &str,
    default_wasi: bool,
    extra_seeds: &BTreeSet<String>,
) -> Result<(String, BTreeSet<String>)> {
    check_module_support(&BashBackend, module)?;
    let gen = Gen {
        module,
        default_wasi,
        prefix,
        rt_prefix,
        uses: RefCell::new(extra_seeds.clone()),
        scratch: Cell::new(0),
        scratch_max: Cell::new(0),
        needs_ci: Cell::new(false),
    };
    let mut w = CodeWriter::new("\t");
    gen.body(&mut w);
    Ok((w.finish(), gen.uses.into_inner()))
}

pub struct BashBackend;

impl Backend for BashBackend {
    fn name(&self) -> &str {
        "bash"
    }

    fn file_extension(&self) -> &str {
        "sh"
    }

    fn has_wasi_p1(&self, name: &str) -> bool {
        bundler().has_unit(&format!("wasi/{name}"))
    }

    fn feature_status(&self, feature: Feature) -> SupportStatus {
        match feature {
            // The ADR-5 softfloat covers the full float surface; the harness now treats any float skip as a hard failure (ADR-8).
            Feature::Floats => SupportStatus::Supported,
            // Defined tables now live in per-index array families keyed by structural type keys, so more than one table lowers directly.
            Feature::MultipleTables => SupportStatus::Supported,
            // Imported globals alias the provider's cell via a `declare -gn` nameref (ADR-35); mutable and immutable both work through it.
            Feature::ImportedGlobals => SupportStatus::Supported,
            // Imported memory aliases the provider's mem/pages/max_pages triplet via `declare -gn` namerefs, keyed off the owning module's flattened prefix (ADR-35); every mem/WASI unit and the inline MemoryGrow/MemorySize lowering work unchanged.
            Feature::ImportedMemories => SupportStatus::Supported,
            // Imported tables alias the provider's array/type-key array/size triplet via `declare -gn` namerefs, keyed off the target table's own base name (ADR-35); tab_init, call_indirect, and active element segments into a shared table all work unchanged through the nameref.
            Feature::ImportedTables => SupportStatus::Supported,
            // Passive/declared element segments, ref.null items, and table.init/copy/elem.drop all lower onto the same `<p>t<i>`/`<p>t<i>ty` table arrays and `<p>elem<n>`/ `<p>elem<n>ty` staging arrays as the active-segment path (tab/init.sh, tab/copy.sh).
            Feature::TableBulkOps => SupportStatus::Supported,
            _ => SupportStatus::Unsupported,
        }
    }

    fn generate(&self, module: &Module, opts: &GenOptions) -> Result<Vec<OutputFile>> {
        // Standalone output is a self-contained program: its prefix is fixed, not derived (ADR-63). Library output uses the requested name (lowercased) after validating it.
        let prefix = if opts.mode == Mode::Standalone {
            STANDALONE_PREFIX.to_string()
        } else {
            check_module_name(&opts.module_name)?;
            func_prefix(&opts.module_name)
        };

        // The status mappings in the standalone main need these even when the module itself never references them.
        let mut extra_seeds = BTreeSet::new();
        if opts.mode == Mode::Standalone {
            extra_seeds.insert("rt/trap".to_string());
            extra_seeds.insert("rt/exit".to_string());
        }

        // Embedded output carries its own runtime copy under its own prefix (ADR-62), so two generated scripts sourced into one shell define disjoint function sets; an Alias artifact calls the shared flat names instead.
        let rt_prefix = match &opts.runtime {
            dewasm_backend::RuntimeLinkage::Embedded => prefix.as_str(),
            dewasm_backend::RuntimeLinkage::Alias(_) => "",
        };
        let (src, units) =
            generate_module_inner(module, &prefix, rt_prefix, opts.default_wasi, &extra_seeds)?;

        let mut out = String::new();
        if opts.mode == Mode::Standalone {
            out.push_str("#!/usr/bin/env bash\n");
        }
        out.push_str("# Generated by dewasm. Do not edit.\n");
        out.push_str(&format!(
            "# Requires bash >= 5. Source this file, then call {prefix}init and\n\
             # {prefix}invoke <export> [args...]; results are returned in R0, R1, ...\n\
             # Cross-module linking (ADR-35): supply imported *functions* in the\n\
             # IMPORTS associative array ([module.name]=command); supply any other\n\
             # import kind by pointing PROVIDERS[module] at a prefix <q> owning the\n\
             # per-kind export maps <q>EXPORTS / <q>GLOBAL_EXPORTS / <q>TABLE_EXPORTS\n\
             # / <q>MEMORY_EXPORTS — the shape another generated module already has.\n\
             # This artifact's runtime carries the same prefix ({prefix}rt_trap,\n\
             # {prefix}mem_i32_load, ...), so several converted scripts coexist in\n\
             # one shell; TRAP_MSG, EXIT_CODE and R0.. are the shared protocol.\n\n"
        ));
        match &opts.runtime {
            dewasm_backend::RuntimeLinkage::Embedded => {
                out.push_str(&prefix_runtime_names(
                    &bundler().bundle(&units, 0)?,
                    &prefix,
                ));
                out.push('\n');
            }
            // Runtime functions are global names in bash; an alias has nothing to emit as long as the shared bundle is sourced.
            dewasm_backend::RuntimeLinkage::Alias(_) => {}
        }
        out.push_str(&src);

        if opts.mode == Mode::Standalone {
            let mut w = CodeWriter::new("\t");
            w.line("");
            w.line("if [[ ${BASH_SOURCE[0]} == \"$0\" ]]; then");
            w.indent();
            // Each wasm call nests one native bash function call (ADR-11), and a deeply recursive guest (e.g. QuickJS's interactive REPL, whose startup alone reaches tens of thousands of frames) can exhaust the *process's* C stack — not the bounded, trappable wasm one (FUNCNEST) — and crash with a real SIGSEGV rather than a caught wasm trap. Raise the soft rlimit to the max this process is allowed before running any guest code; both attempts degrade silently (`|| true`) since a sandboxed environment may refuse both, in which case behavior is unchanged from before this line existed.
            w.line("ulimit -s unlimited 2>/dev/null || ulimit -s \"$(ulimit -Hs)\" 2>/dev/null || true");
            if wasi_bundled(module, opts.default_wasi) {
                // Standalone runtime interface (ADR-31): consume a leading run of `--dir HOST::GUEST` flags into WASI_DIRS (wasmtime-style), stopping at `--` or the first non-flag token; the rest is the guest's argv[1..]. The Bash backend now honors --dir with real filesystem support (ADR-34), mirroring the Ruby standalone parser.
                w.line("WASI_DIRS=()");
                w.line("while (( $# )); do");
                w.line("\tcase \"$1\" in");
                w.line("\t\t--) shift; break ;;");
                w.line("\t\t--dir) shift; [[ $# -gt 0 ]] || { echo \"--dir requires a HOST::GUEST argument\" >&2; exit 2; }; WASI_DIRS+=(\"$1\"); shift ;;");
                w.line("\t\t--dir=*) WASI_DIRS+=(\"${1#--dir=}\"); shift ;;");
                w.line("\t\t*) break ;;");
                w.line("\tesac");
                w.line("done");
                w.line("WASI_ARGS=(\"${0##*/}\" \"$@\")");
                w.line("WASI_ENV=()");
                w.line("for __n in $(compgen -e); do WASI_ENV+=(\"$__n=${!__n}\"); done");
            }
            w.line(format!(
                "{prefix}init || {{ echo \"init failed (status $?): $TRAP_MSG\" >&2; exit 1; }}"
            ));
            w.line(format!("{prefix}invoke '_start'"));
            w.line("__st=$?");
            w.line("if (( __st == 133 )); then exit $(( EXIT_CODE & 0xff )); fi");
            w.line("if (( __st == 134 )); then echo \"trap: $TRAP_MSG\" >&2; exit 134; fi");
            w.line("exit $__st");
            w.dedent();
            w.line("fi");
            out.push_str(&w.finish());
        }
        Ok(vec![OutputFile {
            name: format!("{}.sh", opts.module_name),
            contents: out.into_bytes(),
        }])
    }
}

/// The function/state prefix a `--mode standalone` program uses (ADR-63): fixed, since nothing outside a self-contained program observes it.
pub const STANDALONE_PREFIX: &str = "program_";

/// The library-mode module name must be a single identifier `[A-Za-z_][A-Za-z0-9_]*` (ADR-63). Bash has no case-carrying namespace — every generated name is a global shell identifier — so the name is *lowercased* to build the prefix; that is the one deliberate mapping left in the product, and it is total and fully specified, unlike the sanitizers ADR-63 removed.
fn check_module_name(name: &str) -> Result<()> {
    if is_ident(
        name,
        |c| c.is_ascii_alphabetic() || c == '_',
        |c| c.is_ascii_alphanumeric() || c == '_',
    ) {
        Ok(())
    } else {
        Err(module_name_error(
            "bash",
            name,
            "a single identifier matching [A-Za-z_][A-Za-z0-9_]* (e.g. add, Sqlite3Shell)",
        ))
    }
}

/// The state/function prefix of a *validated* module name: `Sqlite3Shell` -> `sqlite3shell_`, `add` -> `add_`. Public so multi-module e2e cases (`compose_modules`) can derive each module's prefix the same way `generate` does.
pub fn func_prefix(module_name: &str) -> String {
    format!("{}_", module_name.to_ascii_lowercase())
}

/// `wasi_unstable` (snapshot 0) shares the ABI of preview 1 for everything implemented here except fd_seek's whence encoding, and fd_seek is ESPIPE-only on this backend anyway.
const WASI_MODULES: &[&str] = &["wasi_snapshot_preview1", "wasi_unstable"];

fn is_wasi_module(name: &str) -> bool {
    WASI_MODULES.contains(&name)
}

/// Whether the generated module bundles the built-in WASI as an import fallback (and therefore consumes the WASI_ARGS/WASI_ENV arrays).
fn wasi_bundled(module: &Module, default_wasi: bool) -> bool {
    default_wasi
        && module
            .imported_funcs
            .iter()
            .any(|f| is_wasi_module(&f.module) && bundler().has_unit(&format!("wasi/{}", f.name)))
}

/// Single-quoted bash string; `'` is the only character needing an escape.
fn bash_str(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

fn temp(t: Temp) -> String {
    format!("s{}", t.depth)
}

struct Gen<'a> {
    module: &'a Module,
    default_wasi: bool,
    prefix: &'a str,
    /// Prefix every runtime function name carries (see [`generate_module_inner`]).
    rt_prefix: &'a str,
    /// Runtime units the generated code references.
    uses: RefCell<BTreeSet<String>>,
    /// Per-statement scratch variable counter and its per-function peak (`__t<n>` locals hold helper results used as nested operands).
    scratch: Cell<u32>,
    scratch_max: Cell<u32>,
    /// Whether the current function needs the call_indirect scratch vars.
    needs_ci: Cell<bool>,
}

impl<'a> Gen<'a> {
    fn use_unit(&self, id: &str) {
        self.uses.borrow_mut().insert(id.to_string());
    }

    /// The command name of runtime function `name` (`"rt_trap"`, `"mem_init"`, ...) as this artifact spells it.
    fn rt(&self, name: &str) -> String {
        format!("{}{name}", self.rt_prefix)
    }

    fn body(&self, w: &mut CodeWriter) {
        self.init(w);
        w.line("");
        self.invoke_fn(w);
        w.line("");
        self.global_get_fn(w);
        // WASI units take the state prefix as their first argument; imports are bound to bare command names taking only the guest's arguments, so each bundled syscall gets a per-module wrapper baking the prefix in. The wrapper is `<p>imp_wasi_<name>`, not `<p>wasi_<name>`: the latter is the *unit's* own name once the artifact's runtime carries the prefix (ADR-62), and a wrapper of that name would call itself.
        if self.default_wasi {
            let wrappers: BTreeSet<&str> = self
                .module
                .imported_funcs
                .iter()
                .filter(|f| {
                    is_wasi_module(&f.module) && bundler().has_unit(&format!("wasi/{}", f.name))
                })
                .map(|f| f.name.as_str())
                .collect();
            for name in wrappers {
                let p = self.prefix;
                w.line("");
                w.line(format!("{p}imp_wasi_{name}() {{"));
                w.line(format!("\t{} {p} \"$@\"", self.rt(&format!("wasi_{name}"))));
                w.line("}");
            }
        }
        for (i, func) in self.module.funcs.iter().enumerate() {
            w.line("");
            let idx = self.module.num_imported_funcs() as usize + i;
            self.function(w, idx as u32, func);
        }
    }

    fn init(&self, w: &mut CodeWriter) {
        let m = self.module;
        let p = self.prefix;
        let resolve = self.rt("rt_resolve_import");
        let link_err = self.rt("rt_link_err");
        w.line(format!("{p}init() {{"));
        w.indent();
        // Emission order mirrors the Ruby backend (ADR-35): import registries, memory, tables, WASI state, then imports resolved kind by kind, then defined state, then export maps, then start.
        let num_imported_globals = m.imported_globals.len();
        let has_imports = !m.imported_funcs.is_empty()
            || !m.imported_globals.is_empty()
            || !m.imported_tables.is_empty()
            || m.imported_memory.is_some();
        if has_imports {
            // Guard-declare the two import registries up front: memory resolution (right below) needs PROVIDERS before the func/global import loops that used to be the first users of it. `declare -gA` never clears an existing array, so a caller's pre-populated IMPORTS (func overrides) / PROVIDERS (per-module export-map prefixes) survive, while an unset one becomes an empty associative array rather than being treated as indexed with its keys evaluated as arithmetic.
            w.line("declare -gA IMPORTS PROVIDERS");
        }
        // Imported memory (ADR-35): resolve the provider's memown prefix and alias its mem/pages/max_pages triplet in via `declare -gn` namerefs, so every mem/WASI/MemoryGrow/MemorySize unit keeps working unchanged whether the memory is owned locally or by another module. `<p>memown` records the flattened owning prefix (not a nameref itself) so a re-export just forwards the string, keeping any further nameref chain at depth 1.
        if let Some(import) = &m.imported_memory {
            self.use_unit("rt/resolve_import");
            self.use_unit("rt/link_err");
            let mm = bash_str(&import.module);
            let nn = bash_str(&import.name);
            let msg = bash_str(&format!("missing import {}.{}", import.module, import.name));
            w.line(format!("{resolve} {mm} {nn} memory || return $?"));
            w.line(format!(
                "[[ -n $RESOLVED ]] || {{ {link_err} {msg}; return $?; }}"
            ));
            w.line(format!(
                "declare -gn {p}mem=${{RESOLVED}}mem {p}pages=${{RESOLVED}}pages {p}max_pages=${{RESOLVED}}max_pages"
            ));
            w.line(format!("{p}memown=$RESOLVED"));
        }
        if let Some(mem) = &m.memory {
            // Linear memory is an *associative* array, one byte per element (ADR-51): bash indexed arrays are linked lists (O(distance) access), assoc arrays are hash tables (O(1)), which is ~110x faster on the random multi-MB access real apps do. `declare -gA` (never plain `<p>mem=()`, which would create an indexed array) with `=()` also empties any array a re-instantiation left behind.
            w.line(format!("declare -gA {p}mem=()"));
            w.line(format!("{p}pages={}", mem.min_pages));
            w.line(format!("{p}max_pages={}", mem.max_pages.unwrap_or(65536)));
            w.line(format!("{p}memown={p}"));
        }
        // Imported tables (ADR-35): resolve before the defined tables so both share the unified index space. Unlike memory, a table's derived state (`t<i>`/`t<i>ty`/`t<i>sz`) does share one base name, so `rt_resolve_import`'s table kind resolves to the target's variable name directly (already flattened by the exporting module's TABLE_EXPORTS, mirroring imported globals) and each nameref points straight at the real array, one hop.
        for (i, import) in m.imported_tables.iter().enumerate() {
            self.use_unit("rt/resolve_import");
            self.use_unit("rt/link_err");
            let mm = bash_str(&import.module);
            let nn = bash_str(&import.name);
            let msg = bash_str(&format!("missing import {}.{}", import.module, import.name));
            w.line(format!("{resolve} {mm} {nn} table || return $?"));
            w.line(format!(
                "[[ -n $RESOLVED ]] || {{ {link_err} {msg}; return $?; }}"
            ));
            w.line(format!(
                "declare -gn {p}t{i}=$RESOLVED {p}t{i}ty=${{RESOLVED}}ty {p}t{i}sz=${{RESOLVED}}sz"
            ));
        }
        // Per unified-index-space defined table (imported ++ defined). The index base keeps room for the imported ones just above.
        for (i, table) in m.tables.iter().enumerate() {
            let idx = m.num_imported_tables() as usize + i;
            w.line(format!("{p}t{idx}=()"));
            w.line(format!("{p}t{idx}ty=()"));
            w.line(format!("{p}t{idx}sz={}", table.min));
        }
        // The bundled WASI's state is only *needed* by an import that actually falls back to it (ADR-7): one the embedder supplied through IMPORTS/PROVIDERS never reads a `<p>w*` variable. So the import loop below records whether any fallback happened, and the state is built iff one did — the shell-variable counterpart of the other backends' lazy `@wasi ||=` construction, and the observable the `custom_wasi_provider`/`partial_override` cases turn on. Still eager within `<p>init`: nothing is deferred to the first syscall, so ADR-34's preopen validation keeps failing instantiation rather than a later call.
        let wasi_state = wasi_bundled(m, self.default_wasi);
        if wasi_state {
            w.line("local __wasi_fb=0");
        }
        for (i, import) in m.imported_funcs.iter().enumerate() {
            self.use_unit("rt/resolve_import");
            let mm = bash_str(&import.module);
            let nn = bash_str(&import.name);
            w.line(format!("{resolve} {mm} {nn} func || return $?"));
            w.line(format!("{p}if{i}=$RESOLVED"));
            if is_wasi_module(&import.module) && self.default_wasi {
                // Fallback order (ADR-7's bash shape): resolved import -> bundled WASI unit via a per-module prefix wrapper -> ENOSYS stub for known-but-unimplemented syscalls.
                let unit = format!("wasi/{}", import.name);
                if bundler().has_unit(&unit) {
                    self.use_unit(&unit);
                    w.line(format!(
                        "[[ -n ${p}if{i} ]] || {{ {p}if{i}={p}imp_wasi_{}; __wasi_fb=1; }}",
                        import.name
                    ));
                } else {
                    self.use_unit("rt/enosys");
                    w.line(format!(
                        "[[ -n ${p}if{i} ]] || {p}if{i}={}",
                        self.rt("rt_enosys")
                    ));
                }
            } else {
                self.use_unit("rt/link_err");
                let msg = bash_str(&format!("missing import {}.{}", import.module, import.name));
                w.line(format!(
                    "[[ -n ${p}if{i} ]] || {{ {link_err} {msg}; return $?; }}"
                ));
            }
        }
        if wasi_state {
            // Callers set the WASI_ARGS/WASI_ENV/WASI_DIRS arrays before init (the bash analogue of Ruby's args:/env:/preopens: keywords); stdio fds are preopened and fd_read/fd_write track per-fd offsets. wnext is the next fd; wpush is the stdin pushback buffer (a space-separated byte-ordinal list) shared by fd_read and poll_oneoff; init_preopens registers the --dir mounts and the filesystem fd-table arrays, failing init loudly on an unresolvable host (ADR-34).
            w.line("if (( __wasi_fb )); then");
            w.indent();
            w.line(format!("{p}wargs=(\"${{WASI_ARGS[@]}}\")"));
            w.line(format!("{p}wenv=(\"${{WASI_ENV[@]}}\")"));
            w.line(format!("{p}wfds=([0]=1 [1]=1 [2]=1)"));
            w.line(format!("{p}wtell=([0]=0 [1]=0 [2]=0)"));
            w.line(format!("{p}wnext=3"));
            w.line(format!("{p}wpush=''"));
            self.use_unit("wasi/init_preopens");
            w.line(format!("{} {p} || return 1", self.rt("wasi_init_preopens")));
            w.dedent();
            w.line("fi");
        }
        // Imported globals: resolve the provider's cell and alias it in under the unified index with a `declare -gn` nameref, so reads (`(( x = <p>g<i> ))`), mutable writes (`(( <p>g<i> = v ))`), and init-expr `global.get` offsets all reach the shared cell (ADR-35).
        for (i, import) in m.imported_globals.iter().enumerate() {
            self.use_unit("rt/resolve_import");
            self.use_unit("rt/link_err");
            let mm = bash_str(&import.module);
            let nn = bash_str(&import.name);
            let msg = bash_str(&format!("missing import {}.{}", import.module, import.name));
            w.line(format!("{resolve} {mm} {nn} global || return $?"));
            w.line(format!(
                "[[ -n $RESOLVED ]] || {{ {link_err} {msg}; return $?; }}"
            ));
            w.line(format!("declare -gn {p}g{i}=$RESOLVED"));
        }
        for (i, global) in m.globals.iter().enumerate() {
            self.scratch.set(0);
            let idx = num_imported_globals + i;
            self.emit_assign(w, &format!("{p}g{idx}"), &global.init);
        }
        for (n, elem) in m.elems.iter().enumerate() {
            // Stage the segment as a temporary element array (function command names, `''` for a `ref.null` item) plus its structural type keys (same convention, `''` for the null items), mirroring the data-segment mem_init staging below. `ElemItem::Global` never reaches here: a ref-typed global (the only kind `global.get` could target inside an elem expression) is rejected by dewasm-core's `val_type` as soon as the Global/Import section is parsed (module.rs), which happens before the Element section — so a module containing one never makes it past conversion in the first place.
            let mut names = Vec::new();
            let mut keys = Vec::new();
            for item in &elem.items {
                match item {
                    ElemItem::Func(func_idx) => {
                        names.push(self.func_ref(*func_idx));
                        keys.push(format!("'{}'", self.func_type_key(*func_idx)));
                    }
                    ElemItem::Null => {
                        names.push("''".to_string());
                        keys.push("''".to_string());
                    }
                    ElemItem::Global(_) => {
                        unreachable!("ref-typed global element item reached the bash backend")
                    }
                }
            }
            match &elem.kind {
                ElemKind::Declared => {
                    // Never copied into a table; keep the pair of arrays empty so a stray table.init/elem.drop against this index is a harmless no-op-shaped array.
                    w.line(format!("{p}elem{n}=()"));
                    w.line(format!("{p}elem{n}ty=()"));
                }
                ElemKind::Passive => {
                    w.line(format!("{p}elem{n}=({})", names.join(" ")));
                    w.line(format!("{p}elem{n}ty=({})", keys.join(" ")));
                }
                ElemKind::Active {
                    table_index,
                    offset,
                } => {
                    self.scratch.set(0);
                    self.use_unit("tab/init");
                    w.line(format!("{p}elem{n}=({})", names.join(" ")));
                    w.line(format!("{p}elem{n}ty=({})", keys.join(" ")));
                    let off = self.value(w, offset);
                    w.line(format!(
                        "{} {p}t{table_index} {p}elem{n} $(( {off} )) 0 {} || return $?",
                        self.rt("tab_init"),
                        elem.items.len()
                    ));
                    // Active segments are auto-dropped right after instantiation (spec: table.init then an implicit elem.drop), so clear the staging array the same way an explicit ElemDrop would — a later table.init against this segment then traps 'out of bounds table access' like a genuinely dropped one.
                    w.line(format!("{p}elem{n}=()"));
                    w.line(format!("{p}elem{n}ty=()"));
                }
            }
        }
        for (i, data) in m.datas.iter().enumerate() {
            let bytes = data
                .data
                .iter()
                .map(|b| b.to_string())
                .collect::<Vec<_>>()
                .join(" ");
            match &data.offset {
                Some(offset) => {
                    self.scratch.set(0);
                    w.line(format!("{p}data{i}=({bytes})"));
                    let off = self.value(w, offset);
                    self.use_unit("mem/init");
                    w.line(format!(
                        "{} {p} {p}data{i} $(( {off} )) 0 {} || return $?",
                        self.rt("mem_init"),
                        data.data.len()
                    ));
                    w.line(format!("{p}data{i}=()"));
                }
                None => w.line(format!("{p}data{i}=({bytes})")),
            }
        }

        let mut entries = Vec::new();
        for export in &m.exports {
            if let ExportKind::Func(idx) = export.kind {
                entries.push(format!(
                    "[{}]={}",
                    bash_str(&export.name),
                    self.func_ref(idx)
                ));
            }
        }
        w.line(format!("declare -gA {p}EXPORTS=({})", entries.join(" ")));
        let mut gentries = Vec::new();
        for export in &m.exports {
            if let ExportKind::Global(idx) = export.kind {
                // Flatten to the underlying cell's variable name so a consumer's nameref stays depth <=1 (ADR-35): an exported imported global is itself a `<p>g<i>` nameref, so publish its target (`${!<p>g<i>}`); a defined global publishes its own literal variable name.
                let value = if (idx as usize) < num_imported_globals {
                    format!("${{!{p}g{idx}}}")
                } else {
                    format!("{p}g{idx}")
                };
                gentries.push(format!("[{}]={value}", bash_str(&export.name)));
            }
        }
        w.line(format!(
            "declare -gA {p}GLOBAL_EXPORTS=({})",
            gentries.join(" ")
        ));
        let mut mentries = Vec::new();
        for export in &m.exports {
            if let ExportKind::Memory = export.kind {
                // Same flattening as globals, but the value is the owning module's prefix (`<p>memown`), not a single variable name: memory's derived state (`mem`/`pages`/`max_pages`) needs the prefix to rebuild all three suffixes on the importing side, so `rt_resolve_import`'s memory kind resolves to a prefix rather than one variable name (ADR-35).
                mentries.push(format!("[{}]=${p}memown", bash_str(&export.name)));
            }
        }
        w.line(format!(
            "declare -gA {p}MEMORY_EXPORTS=({})",
            mentries.join(" ")
        ));
        let num_imported_tables = m.num_imported_tables() as usize;
        let mut tentries = Vec::new();
        for export in &m.exports {
            if let ExportKind::Table(idx) = export.kind {
                // Flatten to the underlying array's base name, exactly like a global export (ADR-35): an exported imported table is itself a `<p>t<i>` nameref, so publish its target (`${!<p>t<i>}`); a defined table publishes its own literal base name.
                let value = if (idx as usize) < num_imported_tables {
                    format!("${{!{p}t{idx}}}")
                } else {
                    format!("{p}t{idx}")
                };
                tentries.push(format!("[{}]={value}", bash_str(&export.name)));
            }
        }
        w.line(format!(
            "declare -gA {p}TABLE_EXPORTS=({})",
            tentries.join(" ")
        ));

        if let Some(start) = m.start {
            w.line(format!("{} || return $?", self.call_cmd(start, &[])));
        }
        w.line("return 0");
        w.dedent();
        w.line("}");
    }

    fn invoke_fn(&self, w: &mut CodeWriter) {
        let p = self.prefix;
        w.line(format!("{p}invoke() {{"));
        w.indent();
        w.line("local __name=$1");
        w.line("shift");
        w.line(format!("local __fn=${{{p}EXPORTS[$__name]-}}"));
        w.line("if [[ -z $__fn ]]; then");
        w.indent();
        w.line("echo \"no such export: $__name\" >&2");
        w.line("return 1");
        w.dedent();
        w.line("fi");
        w.line("\"$__fn\" \"$@\"");
        w.dedent();
        w.line("}");
    }

    fn global_get_fn(&self, w: &mut CodeWriter) {
        let p = self.prefix;
        w.line(format!("{p}global_get() {{"));
        w.indent();
        w.line(format!("local __var=${{{p}GLOBAL_EXPORTS[$1]-}}"));
        w.line("if [[ -z $__var ]]; then");
        w.indent();
        w.line("echo \"no such global export: $1\" >&2");
        w.line("return 1");
        w.dedent();
        w.line("fi");
        w.line("R0=${!__var}");
        w.line("return 0");
        w.dedent();
        w.line("}");
    }

    fn func_type_key(&self, func_idx: u32) -> String {
        let idx = func_idx as usize;
        let imports = self.module.imported_funcs.len();
        let ty = if idx < imports {
            self.module.imported_funcs[idx].type_idx
        } else {
            self.module.funcs[idx - imports].type_idx
        };
        self.type_key(ty)
    }

    /// A structural key for a function type, e.g. `i32,i64->f32`. call_indirect compares types structurally, and a table can be shared across independently generated modules (imported tables), so the runtime type tag must not be a module-local numeric index — those disagree across modules. Deriving the tag from the type's shape makes it match regardless of each module's type section.
    fn type_key(&self, type_idx: u32) -> String {
        let ty = &self.module.types[type_idx as usize];
        let names = |tys: &[ValType]| {
            tys.iter()
                .map(|t| match t {
                    ValType::I32 => "i32",
                    ValType::I64 => "i64",
                    ValType::F32 => "f32",
                    ValType::F64 => "f64",
                    ValType::FuncRef => "funcref",
                })
                .collect::<Vec<_>>()
                .join(",")
        };
        format!("{}->{}", names(&ty.params), names(&ty.results))
    }

    /// The command name for the function (used in tables and exports).
    fn func_ref(&self, func_idx: u32) -> String {
        if (func_idx as usize) < self.module.imported_funcs.len() {
            format!("${}if{func_idx}", self.prefix)
        } else {
            format!("{}f{func_idx}", self.prefix)
        }
    }

    fn call_cmd(&self, func_idx: u32, args: &[String]) -> String {
        let target = if (func_idx as usize) < self.module.imported_funcs.len() {
            format!("\"${{{}if{func_idx}}}\"", self.prefix)
        } else {
            format!("{}f{func_idx}", self.prefix)
        };
        if args.is_empty() {
            target
        } else {
            format!("{target} {}", args.join(" "))
        }
    }

    fn function(&self, w: &mut CodeWriter, idx: u32, func: &dewasm_core::ir::Func) {
        let ty = &self.module.types[func.type_idx as usize];
        self.scratch_max.set(0);
        self.needs_ci.set(false);

        let mut bw = CodeWriter::new("\t");
        bw.indent();
        let mut frames = Frames { stack: Vec::new() };
        self.stmts(&mut bw, &func.body, &mut frames);
        bw.line("return 0");
        let body = bw.finish();

        w.line(format!("{}f{idx}() {{", self.prefix));
        w.indent();
        let mut decls: Vec<String> = (0..ty.params.len())
            .map(|i| format!("l{i}=\"${{{}}}\"", i + 1))
            .collect();
        for i in 0..func.locals.len() {
            decls.push(format!("l{}=0", ty.params.len() + i));
        }
        if !decls.is_empty() {
            w.line(format!("local {}", decls.join(" ")));
        }
        let mut depths: Vec<u32> = func.temps.iter().map(|t| t.depth).collect();
        depths.dedup();
        if !depths.is_empty() {
            let names = depths
                .iter()
                .map(|d| format!("s{d}"))
                .collect::<Vec<_>>()
                .join(" ");
            w.line(format!("local {names}"));
        }
        let mut extras = Vec::new();
        for t in 0..self.scratch_max.get() {
            extras.push(format!("__t{t}"));
        }
        if self.needs_ci.get() {
            extras.push("__x".to_string());
            extras.push("__fn".to_string());
        }
        if !extras.is_empty() {
            w.line(format!("local {}", extras.join(" ")));
        }
        w.dedent();
        w.raw(&body);
        w.line("}");
    }

    fn stmts(&self, w: &mut CodeWriter, stmts: &[Stmt], f: &mut Frames) {
        for stmt in stmts {
            self.stmt(w, stmt, f);
        }
    }

    fn stmt(&self, w: &mut CodeWriter, stmt: &Stmt, f: &mut Frames) {
        self.scratch.set(0);
        match stmt {
            Stmt::Assign { dst, expr } => self.emit_assign(w, &temp(*dst), expr),
            Stmt::LocalSet { idx, expr } => self.emit_assign(w, &format!("l{idx}"), expr),
            Stmt::GlobalSet { idx, expr } => {
                self.emit_assign(w, &format!("{}g{idx}", self.prefix), expr)
            }
            Stmt::Store {
                op,
                addr,
                value,
                offset,
            } => {
                let method = store_method(*op);
                let ea = self.eff_addr(w, addr, *offset);
                let vfrag = self.value(w, value);
                let v = self.as_var(w, &vfrag);
                self.mem_bounds(w, &ea, access_bytes(method));
                let mem = format!("{}mem", self.prefix);
                for line in store_inline_stmts(method, &mem, &ea, &v) {
                    w.line(line);
                }
            }
            Stmt::Block { label, body } => {
                if label.referenced {
                    f.stack.push(label.id);
                    w.line("while :; do");
                    w.indent();
                    self.stmts(w, body, f);
                    w.line("break");
                    w.dedent();
                    w.line("done");
                    f.stack.pop();
                } else {
                    self.stmts(w, body, f);
                }
            }
            Stmt::Loop { label, body } => {
                if label.referenced {
                    f.stack.push(label.id);
                    w.line("while :; do");
                    w.indent();
                    self.stmts(w, body, f);
                    w.line("break");
                    w.dedent();
                    w.line("done");
                    f.stack.pop();
                } else {
                    // No br targets this loop, so it never repeats.
                    self.stmts(w, body, f);
                }
            }
            Stmt::If {
                label,
                cond,
                then,
                els,
            } => {
                if label.referenced {
                    f.stack.push(label.id);
                    w.line("while :; do");
                    w.indent();
                    self.emit_if(w, cond, then, els, f);
                    w.line("break");
                    w.dedent();
                    w.line("done");
                    f.stack.pop();
                } else {
                    self.emit_if(w, cond, then, els, f);
                }
            }
            Stmt::Br(target) => self.branch(w, target, f),
            Stmt::BrIf { cond, target } => {
                let c = self.value(w, cond);
                w.line(format!("if (( ({c}) != 0 )); then"));
                w.indent();
                self.branch(w, target, f);
                w.dedent();
                w.line("fi");
            }
            Stmt::BrTable {
                index,
                targets,
                default,
            } => {
                if targets.is_empty() {
                    self.branch(w, default, f);
                    return;
                }
                let i = self.value(w, index);
                let v = self.as_var(w, &i);
                w.line(format!("case ${v} in"));
                for (n, target) in targets.iter().enumerate() {
                    w.line(format!("{n})"));
                    w.indent();
                    self.branch(w, target, f);
                    w.line(";;");
                    w.dedent();
                }
                w.line("*)");
                w.indent();
                self.branch(w, default, f);
                w.line(";;");
                w.dedent();
                w.line("esac");
            }
            Stmt::Return { values } => self.return_stmt(w, values),
            Stmt::Call {
                func,
                args,
                results,
            } => {
                let args: Vec<String> = args.iter().map(|a| cmd_arg(&self.value(w, a))).collect();
                w.line(format!("{} || return $?", self.call_cmd(*func, &args)));
                self.assign_results(w, results);
            }
            Stmt::CallIndirect {
                type_idx,
                table_index,
                index,
                args,
                results,
            } => {
                let p = self.prefix;
                let ti = *table_index;
                self.needs_ci.set(true);
                self.use_unit("rt/trap");
                let trap = self.rt("rt_trap");
                let i = self.value(w, index);
                let args: Vec<String> = args.iter().map(|a| cmd_arg(&self.value(w, a))).collect();
                w.line(format!("(( __x = {i} ))"));
                w.line(format!(
                    "(( __x < {p}t{ti}sz )) || {{ {trap} 'undefined element'; return $?; }}"
                ));
                w.line(format!("__fn=${{{p}t{ti}[__x]-}}"));
                w.line(format!(
                    "[[ -n $__fn ]] || {{ {trap} 'uninitialized element'; return $?; }}"
                ));
                // Structural string compare (see type_key): a numeric type id would not survive a table shared across modules.
                w.line(format!(
                    "[[ ${{{p}t{ti}ty[__x]}} == '{}' ]] || {{ {trap} 'indirect call type mismatch'; return $?; }}",
                    self.type_key(*type_idx)
                ));
                let cmd = if args.is_empty() {
                    "\"$__fn\"".to_string()
                } else {
                    format!("\"$__fn\" {}", args.join(" "))
                };
                w.line(format!("{cmd} || return $?"));
                self.assign_results(w, results);
            }
            Stmt::MemoryGrow { dst, delta } => {
                let p = self.prefix;
                let d = self.value(w, delta);
                // Evaluate the delta exactly once by snapshotting the candidate page count: a folded `memory.size` delta reads `pages`, which the grow mutates, so a second textual use of the fragment would see the already-updated value. The destination then takes the old size before `pages` is overwritten.
                let cand = self.as_var(w, &format!("{p}pages + ({d})"));
                w.line(format!("if (( {cand} <= {p}max_pages )); then"));
                w.indent();
                w.line(format!(
                    "(( {} = {p}pages, {p}pages = {cand} ))",
                    temp(*dst)
                ));
                w.dedent();
                w.line("else");
                w.indent();
                w.line(format!("(( {} = 0xffffffff ))", temp(*dst)));
                w.dedent();
                w.line("fi");
            }
            Stmt::MemoryCopy { dst, src, len } => {
                let d = self.value(w, dst);
                let s = self.value(w, src);
                let n = self.value(w, len);
                self.use_unit("mem/copy");
                w.line(format!(
                    "{} {} {} {} {} || return $?",
                    self.rt("mem_copy"),
                    self.prefix,
                    cmd_arg(&d),
                    cmd_arg(&s),
                    cmd_arg(&n)
                ));
            }
            Stmt::MemoryFill { dst, val, len } => {
                let d = self.value(w, dst);
                let v = self.value(w, val);
                let n = self.value(w, len);
                self.use_unit("mem/fill");
                w.line(format!(
                    "{} {} {} {} {} || return $?",
                    self.rt("mem_fill"),
                    self.prefix,
                    cmd_arg(&d),
                    cmd_arg(&v),
                    cmd_arg(&n)
                ));
            }
            Stmt::MemoryInit { seg, dst, src, len } => {
                let d = self.value(w, dst);
                let s = self.value(w, src);
                let n = self.value(w, len);
                self.use_unit("mem/init");
                w.line(format!(
                    "{} {} {}data{seg} {} {} {} || return $?",
                    self.rt("mem_init"),
                    self.prefix,
                    self.prefix,
                    cmd_arg(&d),
                    cmd_arg(&s),
                    cmd_arg(&n)
                ));
            }
            Stmt::DataDrop { seg } => {
                w.line(format!("{}data{seg}=()", self.prefix));
            }
            Stmt::TableInit {
                seg,
                table_index,
                dst,
                src,
                len,
            } => {
                let p = self.prefix;
                let d = self.value(w, dst);
                let s = self.value(w, src);
                let n = self.value(w, len);
                self.use_unit("tab/init");
                w.line(format!(
                    "{} {p}t{table_index} {p}elem{seg} {} {} {} || return $?",
                    self.rt("tab_init"),
                    cmd_arg(&d),
                    cmd_arg(&s),
                    cmd_arg(&n)
                ));
            }
            Stmt::TableCopy {
                dst_table,
                src_table,
                dst,
                src,
                len,
            } => {
                let p = self.prefix;
                let d = self.value(w, dst);
                let s = self.value(w, src);
                let n = self.value(w, len);
                self.use_unit("tab/copy");
                w.line(format!(
                    "{} {p}t{dst_table} {p}t{src_table} {} {} {} || return $?",
                    self.rt("tab_copy"),
                    cmd_arg(&d),
                    cmd_arg(&s),
                    cmd_arg(&n)
                ));
            }
            Stmt::ElemDrop { seg } => {
                let p = self.prefix;
                w.line(format!("{p}elem{seg}=()"));
                w.line(format!("{p}elem{seg}ty=()"));
            }
            Stmt::Unreachable => {
                self.use_unit("rt/trap");
                w.line(format!("{} 'unreachable' || return $?", self.rt("rt_trap")));
            }
            // REASON: DWARF source-line back-mapping is out of scope for Bash (ADR-38); the marker renders nothing, keeping output identical to a non-`--dwarf-line` build.
            Stmt::SourceLine(_) => {}
        }
    }

    fn emit_if(
        &self,
        w: &mut CodeWriter,
        cond: &Expr,
        then: &[Stmt],
        els: &[Stmt],
        f: &mut Frames,
    ) {
        let c = self.value(w, cond);
        w.line(format!("if (( ({c}) != 0 )); then"));
        w.indent();
        if then.is_empty() {
            w.line(":");
        } else {
            self.stmts(w, then, f);
        }
        w.dedent();
        if !els.is_empty() {
            w.line("else");
            w.indent();
            self.stmts(w, els, f);
            w.dedent();
        }
        w.line("fi");
    }

    fn return_stmt(&self, w: &mut CodeWriter, values: &[Expr]) {
        // Command-shaped values are copied into scratch first, so a later helper call cannot clobber an R<i> we already assigned.
        let frags: Vec<String> = values.iter().map(|v| self.value(w, v)).collect();
        for (i, frag) in frags.iter().enumerate() {
            w.line(format!("R{i}=$(( {frag} ))"));
        }
        w.line("return 0");
    }

    fn branch(&self, w: &mut CodeWriter, target: &BrTarget, f: &Frames) {
        match target {
            BrTarget::Return { values } => self.return_stmt(w, values),
            BrTarget::Label {
                label,
                is_loop,
                assigns,
            } => {
                for (dst, src) in assigns {
                    w.line(format!("(( {} = {} ))", temp(*dst), temp(*src)));
                }
                let depth = f.depth_of(*label);
                if *is_loop {
                    w.line(format!("continue {depth}"));
                } else {
                    w.line(format!("break {depth}"));
                }
            }
        }
    }

    fn assign_results(&self, w: &mut CodeWriter, results: &[Temp]) {
        for (i, r) in results.iter().enumerate() {
            w.line(format!("(( {} = R{i} ))", temp(*r)));
        }
    }

    /// Effective-address var for an inline mem access: the load/store address
    /// with the static offset folded in (base+offset in the unsigned 33-bit
    /// range fits bash's signed 64), snapshotted into a plain var so the bounds
    /// check and every byte subscript share one canonical decimal key source.
    fn eff_addr(&self, w: &mut CodeWriter, addr: &Expr, offset: u64) -> String {
        let a = self.value(w, addr);
        let frag = if offset == 0 {
            a
        } else {
            format!("({a}) + {offset}")
        };
        self.as_var(w, &frag)
    }

    /// Inline out-of-bounds check preserving the trap protocol (ADR-11):
    /// compare the effective address against `pages * 65536` (a nameref read
    /// for imported memory, so `memory.grow` on the owner is reflected) and
    /// cascade status 134 on failure.
    fn mem_bounds(&self, w: &mut CodeWriter, ea: &str, n: u32) {
        self.use_unit("rt/trap");
        let p = self.prefix;
        w.line(format!(
            "if (( {ea} + {n} > {p}pages * 65536 )); then {} 'out of bounds memory access'; return $?; fi",
            self.rt("rt_trap")
        ));
    }

    /// Emit an inline load (address snapshot + bounds check), returning the
    /// arithmetic fragment that composes its value directly from memory.
    fn inline_load(&self, w: &mut CodeWriter, op: LoadOp, addr: &Expr, offset: u64) -> String {
        let method = load_method(op);
        let ea = self.eff_addr(w, addr, offset);
        self.mem_bounds(w, &ea, access_bytes(method));
        load_inline_expr(method, &format!("{}mem", self.prefix), &ea)
    }

    fn emit_assign(&self, w: &mut CodeWriter, dst: &str, expr: &Expr) {
        if let Some(frag) = self.arith(expr) {
            w.line(format!("(( {dst} = {frag} ))"));
        } else if let Expr::Load { op, addr, offset } = expr {
            // Load straight into the destination, skipping the R0 hop.
            let frag = self.inline_load(w, *op, addr, *offset);
            w.line(format!("(( {dst} = {frag} ))"));
        } else if self.emit_command(w, expr) {
            w.line(format!("(( {dst} = R0 ))"));
        } else {
            let frag = self.value(w, expr);
            w.line(format!("(( {dst} = {frag} ))"));
        }
    }

    /// Evaluate `expr` to a pure arithmetic fragment, emitting helper commands (with scratch copies) as needed.
    fn value(&self, w: &mut CodeWriter, expr: &Expr) -> String {
        if let Some(frag) = self.arith(expr) {
            return frag;
        }
        match expr {
            Expr::Un(op, a) => {
                let a = self.value(w, a);
                if let Some(frag) = un_inline(*op, &a) {
                    return frag;
                }
                self.rt_cmd(w, un_helper(*op), &[cmd_arg(&a)]);
                self.grab_r0(w)
            }
            Expr::Bin(op, a, b) => {
                let a = self.value(w, a);
                let b = self.value(w, b);
                // Several inline lowerings textually repeat an operand (e.g. I64ShrU references `b` four times); with folded operands that would blow up geometrically. Snapshot non-trivial operands into a scratch var first (as_var is a no-op for a bare var).
                let a = self.as_var(w, &a);
                let b = self.as_var(w, &b);
                if let Some(frag) = bin_inline(*op, &a, &b) {
                    return frag;
                }
                self.rt_cmd(w, bin_helper(*op), &[cmd_arg(&a), cmd_arg(&b)]);
                self.grab_r0(w)
            }
            Expr::Load { op, addr, offset } => {
                // Snapshot the composed value into a scratch var so callers
                // that repeat the operand don't re-read memory.
                let frag = self.inline_load(w, *op, addr, *offset);
                self.as_var(w, &frag)
            }
            Expr::Select { cond, then, els } => {
                let c = self.value(w, cond);
                let t = self.value(w, then);
                let e = self.value(w, els);
                format!("((({c}) != 0 ? ({t}) : ({e})))")
            }
            _ => unreachable!("expression should have lowered to arithmetic"),
        }
    }

    /// Emit `expr` as one helper command leaving its result in R0, when it is directly command-shaped with pure operands. Returns false to let the caller take the generic scratch path.
    fn emit_command(&self, w: &mut CodeWriter, expr: &Expr) -> bool {
        match expr {
            Expr::Un(op, a) => {
                if un_inline_probe(*op) {
                    return false;
                }
                let Some(a) = self.arith(a) else { return false };
                self.rt_cmd(w, un_helper(*op), &[cmd_arg(&a)]);
                true
            }
            Expr::Bin(op, a, b) => {
                if bin_inline_probe(*op) {
                    return false;
                }
                let (Some(a), Some(b)) = (self.arith(a), self.arith(b)) else {
                    return false;
                };
                self.rt_cmd(w, bin_helper(*op), &[cmd_arg(&a), cmd_arg(&b)]);
                true
            }
            // Loads inline directly into their destination via emit_assign /
            // value(); they never take the R0 command path.
            _ => false,
        }
    }

    fn rt_cmd(&self, w: &mut CodeWriter, name: &str, args: &[String]) {
        self.use_unit(&format!("rt/{name}"));
        w.line(format!(
            "{} {} || return $?",
            self.rt(&format!("rt_{name}")),
            args.join(" ")
        ));
    }

    fn grab_r0(&self, w: &mut CodeWriter) -> String {
        let t = self.scratch.get();
        self.scratch.set(t + 1);
        if t + 1 > self.scratch_max.get() {
            self.scratch_max.set(t + 1);
        }
        let name = format!("__t{t}");
        w.line(format!("{name}=$R0"));
        name
    }

    /// Force a fragment into a plain variable (for `case $v in`).
    fn as_var(&self, w: &mut CodeWriter, frag: &str) -> String {
        if frag.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
            && frag.starts_with(|c: char| c.is_ascii_alphabetic() || c == '_')
        {
            return frag.to_string();
        }
        let t = self.scratch.get();
        self.scratch.set(t + 1);
        if t + 1 > self.scratch_max.get() {
            self.scratch_max.set(t + 1);
        }
        let name = format!("__t{t}");
        w.line(format!("(( {name} = {frag} ))"));
        name
    }

    /// Pure arithmetic fragment for `expr`, or None if it needs commands.
    fn arith(&self, expr: &Expr) -> Option<String> {
        match expr {
            Expr::I32Const(v) => Some(v.to_string()),
            // i64 constants are emitted as their signed-64 bit pattern; an unsigned literal above INT64_MAX would be implementation-defined in bash.
            Expr::I64Const(v) => Some(format!("{}", *v as i64)),
            // Floats are their bit patterns (ADR-13): f32 as u32, f64 as the signed-64 pattern (a u64 decimal >= 2^63 would wrap implementation-defined in bash).
            Expr::F32Const(bits) => Some(bits.to_string()),
            Expr::F64Const(bits) => Some(format!("{}", *bits as i64)),
            Expr::Temp(t) => Some(temp(*t)),
            Expr::LocalGet(idx) => Some(format!("l{idx}")),
            Expr::GlobalGet(idx) => Some(format!("{}g{idx}", self.prefix)),
            Expr::Un(op, a) => un_inline(*op, &self.arith(a)?),
            Expr::Bin(op, a, b) => bin_inline(*op, &self.arith(a)?, &self.arith(b)?),
            Expr::Load { .. } => None,
            Expr::Select { cond, then, els } => {
                let c = self.arith(cond)?;
                let t = self.arith(then)?;
                let e = self.arith(els)?;
                Some(format!("((({c}) != 0 ? ({t}) : ({e})))"))
            }
            Expr::MemorySize => Some(format!("{}pages", self.prefix)),
        }
    }
}

struct Frames {
    /// Label ids that occupy a bash loop level, outermost first.
    stack: Vec<u32>,
}

impl Frames {
    fn depth_of(&self, label: u32) -> usize {
        let pos = self
            .stack
            .iter()
            .rposition(|&l| l == label)
            .expect("branch to a label outside the frame stack");
        self.stack.len() - pos
    }
}

/// Command argument for a pure fragment: decimal literals pass through, anything else is evaluated with `$(( ))`.
fn cmd_arg(frag: &str) -> String {
    let digits = frag.strip_prefix('-').unwrap_or(frag);
    if !digits.is_empty() && digits.chars().all(|c| c.is_ascii_digit()) {
        frag.to_string()
    } else {
        format!("\"$(( {frag} ))\"")
    }
}

fn s32_view(x: &str) -> String {
    format!("((({x}) ^ 0x80000000) - 0x80000000)")
}

fn u64_flip(x: &str) -> String {
    format!("(({x}) ^ (1 << 63))")
}

/// Bytes a load/store method touches, for the inline bounds check.
fn access_bytes(method: &str) -> u32 {
    match method {
        "i32_load8_s" | "i32_load8_u" | "i64_load8_s" | "i64_load8_u" | "i32_store8"
        | "i64_store8" => 1,
        "i32_load16_s" | "i32_load16_u" | "i64_load16_s" | "i64_load16_u" | "i32_store16"
        | "i64_store16" => 2,
        "i32_load" | "i64_load32_s" | "i64_load32_u" | "i32_store" | "i64_store32" => 4,
        "i64_load" | "i64_store" => 8,
        _ => unreachable!("unknown mem method {method}"),
    }
}

/// One little-endian byte cell of `<mem>` at effective address `ea` (already a
/// plain integer var): `<mem>[$ea]` for byte 0, `<mem>[$((ea+k))]` for k>0 —
/// the pre-expanded canonical-decimal key the assoc representation needs so it
/// stays on bash's fast subscript path (ADR-51).
fn mem_byte(mem: &str, ea: &str, k: u32) -> String {
    if k == 0 {
        format!("{mem}[${ea}]")
    } else {
        format!("{mem}[$(({ea}+{k}))]")
    }
}

/// Little-endian composition of `n` bytes at `ea`: `b0 | b1<<8 | ...`.
fn le_compose(mem: &str, ea: &str, n: u32) -> String {
    (0..n)
        .map(|k| match k {
            0 => mem_byte(mem, ea, 0),
            _ => format!("{}<<{}", mem_byte(mem, ea, k), k * 8),
        })
        .collect::<Vec<_>>()
        .join(" | ")
}

/// Inline arithmetic reproducing a `mem_<method>` load body: little-endian
/// byte composition with the unit's exact sign-extension form. The i64 top
/// byte `<<56` wraps into the sign bit, which is the signed-64 bit pattern of
/// i64 (ADR-11); narrow signed loads xor/sub the sign bit, and the i32 ones
/// remask to masked-unsigned (ADR-2).
fn load_inline_expr(method: &str, mem: &str, ea: &str) -> String {
    match method {
        "i32_load" => le_compose(mem, ea, 4),
        "i64_load" => le_compose(mem, ea, 8),
        "i32_load8_u" | "i64_load8_u" => mem_byte(mem, ea, 0),
        "i32_load16_u" | "i64_load16_u" => le_compose(mem, ea, 2),
        "i64_load32_u" => le_compose(mem, ea, 4),
        "i32_load8_s" => format!("(({} ^ 0x80) - 0x80) & 0xffffffff", mem_byte(mem, ea, 0)),
        "i32_load16_s" => format!(
            "((({}) ^ 0x8000) - 0x8000) & 0xffffffff",
            le_compose(mem, ea, 2)
        ),
        "i64_load8_s" => format!("({} ^ 0x80) - 0x80", mem_byte(mem, ea, 0)),
        "i64_load16_s" => format!("((({}) ^ 0x8000) - 0x8000)", le_compose(mem, ea, 2)),
        "i64_load32_s" => format!("((({}) ^ 0x80000000) - 0x80000000)", le_compose(mem, ea, 4)),
        _ => unreachable!("unknown load method {method}"),
    }
}

/// Inline byte-store statements reproducing a `mem_<method>` store body: low
/// byte first, `v >> 8*k & 0xff` per cell. The arithmetic right shift on a
/// negative i64 pattern is harmless — `& 0xff` masks the dragged-in sign bits
/// (ADR-11).
fn store_inline_stmts(method: &str, mem: &str, ea: &str, v: &str) -> Vec<String> {
    (0..access_bytes(method))
        .map(|k| {
            let rhs = if k == 0 {
                format!("{v} & 0xff")
            } else {
                format!("{v} >> {} & 0xff", k * 8)
            };
            format!("{}=$(( {rhs} ))", mem_byte(mem, ea, k))
        })
        .collect()
}

/// Inline arithmetic lowering for a unary op, if it has one.
fn un_inline(op: UnOp, a: &str) -> Option<String> {
    use UnOp::*;
    Some(match op {
        I32Eqz | I64Eqz => format!("(({a}) == 0)"),
        I32WrapI64 => format!("(({a}) & 0xffffffff)"),
        I64ExtendI32U => format!("({a})"),
        I64ExtendI32S => s32_view(a),
        I32Extend8S => format!("((((({a}) & 0xff) ^ 0x80) - 0x80) & 0xffffffff)"),
        I32Extend16S => format!("((((({a}) & 0xffff) ^ 0x8000) - 0x8000) & 0xffffffff)"),
        I64Extend8S => format!("(((({a}) & 0xff) ^ 0x80) - 0x80)"),
        I64Extend16S => format!("(((({a}) & 0xffff) ^ 0x8000) - 0x8000)"),
        I64Extend32S => format!("(((({a}) & 0xffffffff) ^ 0x80000000) - 0x80000000)"),
        // Pure bit ops on the float patterns (payload-preserving, as the spec requires for the sign ops); reinterprets are the identity.
        F32Abs => format!("(({a}) & 0x7fffffff)"),
        F32Neg => format!("(({a}) ^ 0x80000000)"),
        F64Abs => format!("(({a}) & 0x7fffffffffffffff)"),
        F64Neg => format!("(({a}) ^ (1 << 63))"),
        I32ReinterpretF32 | I64ReinterpretF64 | F32ReinterpretI32 | F64ReinterpretI64 => {
            format!("({a})")
        }
        _ => return None,
    })
}

/// Whether `un_inline` handles this op (without needing the fragment).
fn un_inline_probe(op: UnOp) -> bool {
    un_inline(op, "0").is_some()
}

fn un_helper(op: UnOp) -> &'static str {
    use UnOp::*;
    match op {
        I32Clz => "i32_clz",
        I32Ctz => "i32_ctz",
        I64Clz => "i64_clz",
        I64Ctz => "i64_ctz",
        I32Popcnt | I64Popcnt => "popcnt",
        F32Ceil => "f32_ceil",
        F32Floor => "f32_floor",
        F32Trunc => "f32_trunc",
        F32Nearest => "f32_nearest",
        F32Sqrt => "f32_sqrt",
        F64Ceil => "f64_ceil",
        F64Floor => "f64_floor",
        F64Trunc => "f64_trunc",
        F64Nearest => "f64_nearest",
        F64Sqrt => "f64_sqrt",
        I32TruncF32S => "i32_trunc_f32_s",
        I32TruncF32U => "i32_trunc_f32_u",
        I32TruncF64S => "i32_trunc_f64_s",
        I32TruncF64U => "i32_trunc_f64_u",
        I64TruncF32S => "i64_trunc_f32_s",
        I64TruncF32U => "i64_trunc_f32_u",
        I64TruncF64S => "i64_trunc_f64_s",
        I64TruncF64U => "i64_trunc_f64_u",
        I32TruncSatF32S => "i32_trunc_sat_f32_s",
        I32TruncSatF32U => "i32_trunc_sat_f32_u",
        I32TruncSatF64S => "i32_trunc_sat_f64_s",
        I32TruncSatF64U => "i32_trunc_sat_f64_u",
        I64TruncSatF32S => "i64_trunc_sat_f32_s",
        I64TruncSatF32U => "i64_trunc_sat_f32_u",
        I64TruncSatF64S => "i64_trunc_sat_f64_s",
        I64TruncSatF64U => "i64_trunc_sat_f64_u",
        F32ConvertI32S => "f32_convert_i32_s",
        F32ConvertI32U => "f32_convert_i32_u",
        F32ConvertI64S => "f32_convert_i64_s",
        F32ConvertI64U => "f32_convert_i64_u",
        F64ConvertI32S => "f64_convert_i32_s",
        F64ConvertI32U => "f64_convert_i32_u",
        F64ConvertI64S => "f64_convert_i64_s",
        F64ConvertI64U => "f64_convert_i64_u",
        F32DemoteF64 => "f32_demote",
        F64PromoteF32 => "f64_promote",
        _ => unreachable!("op {op:?} has an inline lowering"),
    }
}

/// Inline arithmetic lowering for a binary op, if it has one.
fn bin_inline(op: BinOp, a: &str, b: &str) -> Option<String> {
    use BinOp::*;
    Some(match op {
        I32Add => format!("((({a}) + ({b})) & 0xffffffff)"),
        I32Sub => format!("((({a}) - ({b})) & 0xffffffff)"),
        I32Mul => format!("((({a}) * ({b})) & 0xffffffff)"),
        I64Add => format!("(({a}) + ({b}))"),
        I64Sub => format!("(({a}) - ({b}))"),
        I64Mul => format!("(({a}) * ({b}))"),
        I32And | I64And => format!("(({a}) & ({b}))"),
        I32Or | I64Or => format!("(({a}) | ({b}))"),
        I32Xor | I64Xor => format!("(({a}) ^ ({b}))"),
        I32Shl => format!("((({a}) << (({b}) & 31)) & 0xffffffff)"),
        I32ShrU => format!("(({a}) >> (({b}) & 31))"),
        I32ShrS => format!("(({} >> (({b}) & 31)) & 0xffffffff)", s32_view(a)),
        I64Shl => format!("(({a}) << (({b}) & 63))"),
        I64ShrS => format!("(({a}) >> (({b}) & 63))"),
        // Logical right shift over the signed representation: mask off the dragged-in sign bits; a shift count of 0 must bypass the mask because bash takes shift counts mod 64.
        I64ShrU => format!(
            "(((({b}) & 63) == 0 ? ({a}) : ((({a}) >> (({b}) & 63)) & ~(-1 << (64 - (({b}) & 63))))))"
        ),
        I32Eq | I64Eq => format!("(({a}) == ({b}))"),
        I32Ne | I64Ne => format!("(({a}) != ({b}))"),
        I32LtU => format!("(({a}) < ({b}))"),
        I32GtU => format!("(({a}) > ({b}))"),
        I32LeU => format!("(({a}) <= ({b}))"),
        I32GeU => format!("(({a}) >= ({b}))"),
        I32LtS => format!("({} < {})", s32_view(a), s32_view(b)),
        I32GtS => format!("({} > {})", s32_view(a), s32_view(b)),
        I32LeS => format!("({} <= {})", s32_view(a), s32_view(b)),
        I32GeS => format!("({} >= {})", s32_view(a), s32_view(b)),
        I64LtS => format!("(({a}) < ({b}))"),
        I64GtS => format!("(({a}) > ({b}))"),
        I64LeS => format!("(({a}) <= ({b}))"),
        I64GeS => format!("(({a}) >= ({b}))"),
        I64LtU => format!("({} < {})", u64_flip(a), u64_flip(b)),
        I64GtU => format!("({} > {})", u64_flip(a), u64_flip(b)),
        I64LeU => format!("({} <= {})", u64_flip(a), u64_flip(b)),
        I64GeU => format!("({} >= {})", u64_flip(a), u64_flip(b)),
        F32Copysign => format!("((({a}) & 0x7fffffff) | (({b}) & 0x80000000))"),
        F64Copysign => {
            format!("((({a}) & 0x7fffffffffffffff) | (({b}) & (1 << 63)))")
        }
        _ => return None,
    })
}

/// Whether `bin_inline` handles this op (without needing the fragments).
fn bin_inline_probe(op: BinOp) -> bool {
    bin_inline(op, "0", "0").is_some()
}

fn bin_helper(op: BinOp) -> &'static str {
    use BinOp::*;
    match op {
        I32DivS => "i32_div_s",
        I32DivU => "i32_div_u",
        I32RemS => "i32_rem_s",
        I32RemU => "i32_rem_u",
        I64DivS => "i64_div_s",
        I64DivU => "i64_div_u",
        I64RemS => "i64_rem_s",
        I64RemU => "i64_rem_u",
        I32Rotl => "i32_rotl",
        I32Rotr => "i32_rotr",
        I64Rotl => "i64_rotl",
        I64Rotr => "i64_rotr",
        F32Add => "f32_add",
        F32Sub => "f32_sub",
        F32Mul => "f32_mul",
        F32Div => "f32_div",
        F32Min => "f32_min",
        F32Max => "f32_max",
        F64Add => "f64_add",
        F64Sub => "f64_sub",
        F64Mul => "f64_mul",
        F64Div => "f64_div",
        F64Min => "f64_min",
        F64Max => "f64_max",
        F32Eq => "f32_eq",
        F32Ne => "f32_ne",
        F32Lt => "f32_lt",
        F32Gt => "f32_gt",
        F32Le => "f32_le",
        F32Ge => "f32_ge",
        F64Eq => "f64_eq",
        F64Ne => "f64_ne",
        F64Lt => "f64_lt",
        F64Gt => "f64_gt",
        F64Le => "f64_le",
        F64Ge => "f64_ge",
        _ => unreachable!("op {op:?} has an inline lowering"),
    }
}

fn load_method(op: LoadOp) -> &'static str {
    use LoadOp::*;
    match op {
        I32Load => "i32_load",
        I64Load => "i64_load",
        // Floats travel as bit patterns; the integer memory units are exact (ADR-13).
        F32Load => "i32_load",
        F64Load => "i64_load",
        I32Load8S => "i32_load8_s",
        I32Load8U => "i32_load8_u",
        I32Load16S => "i32_load16_s",
        I32Load16U => "i32_load16_u",
        I64Load8S => "i64_load8_s",
        I64Load8U => "i64_load8_u",
        I64Load16S => "i64_load16_s",
        I64Load16U => "i64_load16_u",
        I64Load32S => "i64_load32_s",
        I64Load32U => "i64_load32_u",
    }
}

fn store_method(op: StoreOp) -> &'static str {
    use StoreOp::*;
    match op {
        I32Store => "i32_store",
        I64Store => "i64_store",
        F32Store => "i32_store",
        F64Store => "i64_store",
        I32Store8 => "i32_store8",
        I32Store16 => "i32_store16",
        I64Store8 => "i64_store8",
        I64Store16 => "i64_store16",
        I64Store32 => "i64_store32",
    }
}

/// Lint for the bash runtime units: every reference a unit body makes to another unit must be declared in its `# requires:` header, and every unit function must end with an explicit `return`/`:` — a trailing arithmetic statement would leak status 1 into the `|| return $?` trap cascade (ADR-11). Static half of the ADR-6 drift defence.
#[cfg(test)]
mod units {
    use super::*;
    use std::collections::BTreeSet;

    use regex::Regex;

    #[test]
    fn all_units_bundle() {
        bundler().bundle_all(0).expect("full bundle resolves");
    }

    #[test]
    fn declared_requires_cover_references() {
        let b = bundler();
        let unit_ids: BTreeSet<&str> = b.units().map(|u| u.id.as_str()).collect();
        let call = Regex::new(r"\b(rt|mem|wasi|tab)_([a-z0-9_]+)").unwrap();

        let mut problems = Vec::new();
        for unit in b.units() {
            let declared: BTreeSet<&str> = unit.requires.iter().map(|s| s.as_str()).collect();
            let code: String = unit
                .body
                .lines()
                .filter(|l| !l.trim_start().starts_with('#'))
                .collect::<Vec<_>>()
                .join("\n");
            for cap in call.captures_iter(&code) {
                let dep = format!("{}/{}", &cap[1], &cap[2]);
                if dep == unit.id || declared.contains(dep.as_str()) {
                    continue;
                }
                if !unit_ids.contains(dep.as_str()) {
                    // Longest-match artifacts (e.g. rt_i32 inside rt_i32_clz) cannot occur because the regex is greedy; anything else unknown is a genuine typo.
                    problems.push(format!("{}: references unknown unit {dep}", unit.id));
                    continue;
                }
                problems.push(format!(
                    "{}: uses {}_{} but does not require {dep}",
                    unit.id, &cap[1], &cap[2]
                ));
            }
        }
        assert!(
            problems.is_empty(),
            "unit dependency drift:\n{}",
            problems.join("\n")
        );
    }

    /// `Embedded` linkage renames the runtime per artifact by rewriting every `rt_`/`mem_`/`wasi_`/`tab_` identifier across the bundle text ([`prefix_runtime_names`], ADR-62), which is sound only while such a name is always code. One inside a string literal would be rewritten too, silently changing program-visible text (a trap message, an errno key, a path); no unit has one today, and this keeps it that way.
    #[test]
    fn no_runtime_name_inside_a_string_literal() {
        let call = Regex::new(r"\b(rt|mem|wasi|tab)_[a-z0-9_]+").unwrap();
        let mut problems = Vec::new();
        for unit in bundler().units() {
            for (n, line) in unit.body.lines().enumerate() {
                for lit in string_literals(line) {
                    if let Some(m) = call.find(&lit) {
                        problems.push(format!(
                            "{}:{}: `{}` inside the string literal {lit}",
                            unit.id,
                            n + 1,
                            m.as_str()
                        ));
                    }
                }
            }
        }
        assert!(
            problems.is_empty(),
            "the Embedded runtime rename would rewrite these string literals:\n{}",
            problems.join("\n")
        );
    }

    /// Every single-line quoted string on `line`, stopping at a `#` comment outside quotes (bash starts a comment only at a word boundary). `\` escapes inside double quotes; single quotes have no escapes at all.
    fn string_literals(line: &str) -> Vec<String> {
        let mut out = Vec::new();
        let chars: Vec<char> = line.chars().collect();
        let mut i = 0;
        while i < chars.len() {
            match chars[i] {
                '#' if i == 0 || chars[i - 1].is_whitespace() => break,
                '\\' => i += 2,
                q @ ('\'' | '"') => {
                    let mut lit = String::new();
                    i += 1;
                    while i < chars.len() && chars[i] != q {
                        if q == '"' && chars[i] == '\\' {
                            i += 1;
                            if i >= chars.len() {
                                break;
                            }
                        }
                        lit.push(chars[i]);
                        i += 1;
                    }
                    out.push(lit);
                    i += 1;
                }
                _ => i += 1,
            }
        }
        out
    }

    /// The rewrite moves definitions and call sites together, leaves anything that is not one of the four runtime scopes alone, and respects identifier boundaries (`__mem_x` is a local, not the `mem_x` unit).
    #[test]
    fn prefixing_moves_whole_names_only() {
        let src = "mem_check() {\n  rt_trap 'x'; local __mem_check=1; wasi_fd_write \"${1}mem\"\n}";
        assert_eq!(
            prefix_runtime_names(src, "alpha_"),
            "alpha_mem_check() {\n  alpha_rt_trap 'x'; local __mem_check=1; alpha_wasi_fd_write \"${1}mem\"\n}"
        );
        assert_eq!(prefix_runtime_names(src, ""), src);
    }

    #[test]
    fn unit_functions_end_with_return() {
        let b = bundler();
        let mut problems = Vec::new();
        for unit in b.units() {
            let lines: Vec<&str> = unit.body.lines().collect();
            for (i, line) in lines.iter().enumerate() {
                if *line != "}" {
                    continue;
                }
                let last = lines[..i]
                    .iter()
                    .rev()
                    .find(|l| !l.trim().is_empty())
                    .map(|l| l.trim())
                    .unwrap_or("");
                if !(last.starts_with("return") || last == ":" || last.ends_with("return $?; }")) {
                    problems.push(format!(
                        "{}: function body ends with `{last}` instead of an explicit return",
                        unit.id
                    ));
                }
            }
        }
        assert!(
            problems.is_empty(),
            "unit functions must end with an explicit return (status discipline):\n{}",
            problems.join("\n")
        );
    }
}
