[package]
name = "dewasm-backend-ruby"
description = "Ruby backend for dewasm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
dewasm-core.workspace = true
dewasm-backend.workspace = true

[dev-dependencies]
regex.workspace = true
