#!/usr/bin/env bash
# Build the DOOM Java frontend: fetch the upstream wasm module, run it
# through dewasm to regenerate the Doom.java library, then compile everything
# with plain javac. Doom.java is gitignored and regenerated by this script.
set -euo pipefail
cd "$(dirname "$0")"

script_dir="$(pwd)"
repo_root="$script_dir/../../.."

"$script_dir/../fetch.sh"

(cd "$repo_root" && cargo run -q -p dewasm-cli -- \
  examples/doom/cache/doom.wasm --target java --mode library \
  --module-name Doom -o examples/doom/java/Doom.java)

mkdir -p classes
javac -d classes Main.java Doom.java

echo "build complete: classes/"
